// Auto-generated feed data from awesome-rss-feeds repository
// Generated on: 2025-11-27T11:48:54.466Z
// Source: https://github.com/plenaryapp/awesome-rss-feeds

export interface Feed {
  title: string;
  url: string;
  score: number;
  category?: string;
  country?: string;
}

// Recommended category-based feeds
export const TOPIC_BASED_FEEDS: Record<string, Feed[]> = {
  "android": [
    { title: "All About Android (Audio)", url: "https://feeds.twit.tv/aaa.xml", score: 1.00, category: "android" },
    { title: "Android", url: "https://blog.google/products/android/rss", score: 0.98, category: "android" },
    { title: "Android", url: "https://www.reddit.com/r/android/.rss", score: 0.96, category: "android" },
    { title: "Android Authority", url: "https://www.androidauthority.com/feed", score: 0.94, category: "android" },
    { title: "Android Authority", url: "https://www.youtube.com/feeds/videos.xml?user=AndroidAuthority", score: 0.92, category: "android" },
    { title: "Android Authority Podcast", url: "https://androidauthority.libsyn.com/rss", score: 0.90, category: "android" },
    { title: "Android Central - Android Forums, News, Reviews, Help and Android Wallpapers", url: "http://feeds.androidcentral.com/androidcentral", score: 0.88, category: "android" },
    { title: "Android Central Podcast", url: "http://feeds.feedburner.com/AndroidCentralPodcast", score: 0.86, category: "android" },
    { title: "Android Community", url: "https://androidcommunity.com/feed/", score: 0.84, category: "android" },
    { title: "Android Police – Android news, reviews, apps, games, phones, tablets", url: "http://feeds.feedburner.com/AndroidPolice", score: 0.82, category: "android" },
    { title: "AndroidGuys", url: "https://www.androidguys.com/feed", score: 0.80, category: "android" },
    { title: "Cult of Android", url: "https://www.cultofandroid.com/feed", score: 0.78, category: "android" },
    { title: "Cyanogen Mods", url: "https://www.cyanogenmods.org/feed", score: 0.76, category: "android" },
    { title: "Droid Life", url: "https://www.droid-life.com/feed", score: 0.74, category: "android" },
    { title: "GSMArena.com - Latest articles", url: "https://www.gsmarena.com/rss-news-reviews.php3", score: 0.72, category: "android" },
    { title: "Phandroid", url: "http://feeds2.feedburner.com/AndroidPhoneFans", score: 0.70, category: "android" },
    { title: "TalkAndroid", url: "http://feeds.feedburner.com/AndroidNewsGoogleAndroidForums", score: 0.68, category: "android" },
    { title: "xda-developers", url: "https://data.xda-developers.com/portal-feed", score: 0.66, category: "android" },
  ],
  "android-development": [
    { title: "Android - Buffer Resources", url: "https://buffer.com/resources/android/rss/", score: 1.00, category: "android-development" },
    { title: "Android Developers", url: "https://www.youtube.com/feeds/videos.xml?user=androiddevelopers", score: 0.98, category: "android-development" },
    { title: "Android Developers - Medium", url: "https://medium.com/feed/androiddevelopers", score: 0.96, category: "android-development" },
    { title: "Android Developers Backstage", url: "http://feeds.feedburner.com/blogspot/androiddevelopersbackstage", score: 0.94, category: "android-development" },
    { title: "Android Developers Blog", url: "http://feeds.feedburner.com/blogspot/hsDu", score: 0.92, category: "android-development" },
    { title: "Android Weekly Archive Feed", url: "https://us2.campaign-archive.com/feed?u=887caf4f48db76fd91e20a06d&id=4eb677ad19", score: 0.90, category: "android-development" },
    { title: "Android in Instagram Engineering on Medium", url: "https://instagram-engineering.com/feed/tagged/android", score: 0.88, category: "android-development" },
    { title: "Android in MindOrks on Medium", url: "https://medium.com/feed/mindorks/tagged/android", score: 0.86, category: "android-development" },
    { title: "Android in The Airbnb Tech Blog on Medium", url: "https://medium.com/feed/airbnb-engineering/tagged/android", score: 0.84, category: "android-development" },
    { title: "Dan Lew Codes", url: "https://blog.danlew.net/rss/", score: 0.82, category: "android-development" },
    { title: "Developing Android Apps", url: "https://reddit.com/r/androiddev.rss", score: 0.80, category: "android-development" },
    { title: "Fragmented - The Software Podcast", url: "https://feeds.simplecast.com/LpAGSLnY", score: 0.78, category: "android-development" },
    { title: "Handstand Sam", url: "https://handstandsam.com/feed/", score: 0.76, category: "android-development" },
    { title: "Jake Wharton", url: "https://jakewharton.com/atom.xml", score: 0.74, category: "android-development" },
    { title: "JetBrains News | JetBrains Blog", url: "https://blog.jetbrains.com/blog/feed", score: 0.72, category: "android-development" },
    { title: "Joe Birch", url: "https://joebirch.co/feed", score: 0.70, category: "android-development" },
    { title: "Kotlin", url: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLQ176FUIyIUa6SChjajjVc-LMzxWiz6dy", score: 0.68, category: "android-development" },
    { title: "Kt. Academy - Medium", url: "https://blog.kotlin-academy.com/feed", score: 0.66, category: "android-development" },
    { title: "OkKotlin", url: "https://okkotlin.com/rss.xml", score: 0.64, category: "android-development" },
    { title: "ProAndroidDev - Medium", url: "https://proandroiddev.com/feed", score: 0.62, category: "android-development" },
    { title: "Public Object", url: "https://publicobject.com/rss/", score: 0.60, category: "android-development" },
    { title: "Styling Android", url: "http://feeds.feedburner.com/StylingAndroid", score: 0.58, category: "android-development" },
    { title: "Talking Kotlin", url: "https://feeds.soundcloud.com/users/soundcloud:users:280353173/sounds.rss", score: 0.56, category: "android-development" },
    { title: "The Android Arsenal", url: "https://feeds.feedburner.com/Android_Arsenal", score: 0.54, category: "android-development" },
    { title: "Zac Sweers", url: "https://www.zacsweers.dev/rss/", score: 0.52, category: "android-development" },
    { title: "Zarah Dominguez", url: "https://zarah.dev/feed.xml", score: 0.50, category: "android-development" },
    { title: "chRyNaN Codes", url: "https://chrynan.codes/rss/", score: 0.50, category: "android-development" },
    { title: "droidcon NYC", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSLXy31j2Z0sdDeeAX5JpPw", score: 0.50, category: "android-development" },
    { title: "droidcon SF", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCKubKoe1CBw_-n_GXetEQbg", score: 0.50, category: "android-development" },
    { title: "goobar", url: "https://goobar.io/feed", score: 0.50, category: "android-development" },
    { title: "zsmb.co", url: "https://zsmb.co/index.xml", score: 0.50, category: "android-development" },
  ],
  "apple": [
    { title: "9to5Mac", url: "https://9to5mac.com/feed", score: 1.00, category: "apple" },
    { title: "Apple", url: "https://www.youtube.com/feeds/videos.xml?user=Apple", score: 0.98, category: "apple" },
    { title: "Apple Newsroom", url: "https://www.apple.com/newsroom/rss-feed.rss", score: 0.96, category: "apple" },
    { title: "AppleInsider News", url: "https://appleinsider.com/rss/news/", score: 0.94, category: "apple" },
    { title: "Cult of Mac", url: "https://www.cultofmac.com/feed", score: 0.92, category: "apple" },
    { title: "Daring Fireball", url: "https://daringfireball.net/feeds/main", score: 0.90, category: "apple" },
    { title: "MacRumors", url: "https://www.youtube.com/feeds/videos.xml?user=macrumors", score: 0.88, category: "apple" },
    { title: "MacRumors: Mac News and Rumors - Mac Blog", url: "http://feeds.macrumors.com/MacRumors-Mac", score: 0.86, category: "apple" },
    { title: "MacStories", url: "https://www.macstories.net/feed", score: 0.84, category: "apple" },
    { title: "Macworld.com", url: "https://www.macworld.com/index.rss", score: 0.82, category: "apple" },
    { title: "Marco.org", url: "https://marco.org/rss", score: 0.80, category: "apple" },
    { title: "OS X Daily", url: "http://feeds.feedburner.com/osxdaily", score: 0.78, category: "apple" },
    { title: "The Loop", url: "https://www.loopinsight.com/feed", score: 0.76, category: "apple" },
    { title: "The unofficial Apple community", url: "https://www.reddit.com/r/apple/.rss", score: 0.74, category: "apple" },
    { title: "iMore - The #1 iPhone, iPad, and iPod touch blog", url: "http://feeds.feedburner.com/TheiPhoneBlog", score: 0.72, category: "apple" },
    { title: "r/iPhone", url: "https://www.reddit.com/r/iphone/.rss", score: 0.70, category: "apple" },
  ],
  "architecture": [
    { title: "A Daily Dose of Architecture Books", url: "http://feeds.feedburner.com/archidose", score: 1.00, category: "architecture" },
    { title: "ArchDaily", url: "http://feeds.feedburner.com/Archdaily", score: 0.98, category: "architecture" },
    { title: "Archinect - News", url: "https://archinect.com/feed/1/news", score: 0.96, category: "architecture" },
    { title: "Architectural Digest", url: "https://www.architecturaldigest.com/feed/rss", score: 0.94, category: "architecture" },
    { title: "Architectural Digest", url: "https://www.youtube.com/feeds/videos.xml?user=ArchitecturalDigest", score: 0.92, category: "architecture" },
    { title: "Architecture", url: "https://www.reddit.com/r/architecture/.rss", score: 0.90, category: "architecture" },
    { title: "Architecture – Dezeen", url: "https://www.dezeen.com/architecture/feed/", score: 0.88, category: "architecture" },
    { title: "CONTEMPORIST", url: "https://www.contemporist.com/feed/", score: 0.86, category: "architecture" },
    { title: "Comments on:", url: "https://inhabitat.com/architecture/feed/", score: 0.84, category: "architecture" },
    { title: "Design MilkArchitecture – Design Milk", url: "https://design-milk.com/category/architecture/feed/", score: 0.82, category: "architecture" },
    { title: "Journal", url: "https://architizer.wpengine.com/feed/", score: 0.80, category: "architecture" },
    { title: "Living Big In A Tiny House", url: "https://www.youtube.com/feeds/videos.xml?user=livingbigtinyhouse", score: 0.78, category: "architecture" },
    { title: "The Architect’s Newspaper", url: "https://archpaper.com/feed", score: 0.76, category: "architecture" },
    { title: "architecture – designboom | architecture & design magazine", url: "https://www.designboom.com/architecture/feed/", score: 0.74, category: "architecture" },
  ],
  "beauty": [
    { title: "Beauty - ELLE", url: "https://www.elle.com/rss/beauty.xml/", score: 1.00, category: "beauty" },
    { title: "Beauty - Fashionista", url: "https://fashionista.com/.rss/excerpt/beauty", score: 0.98, category: "beauty" },
    { title: "Beauty – Indian Fashion Blog", url: "https://www.fashionlady.in/category/beauty-tips/feed", score: 0.96, category: "beauty" },
    { title: "Blog – The Beauty Brains", url: "https://thebeautybrains.com/blog/feed/", score: 0.94, category: "beauty" },
    { title: "DORÉ", url: "https://www.wearedore.com/feed", score: 0.92, category: "beauty" },
    { title: "From Head To Toe", url: "http://feeds.feedburner.com/frmheadtotoe", score: 0.90, category: "beauty" },
    { title: "Into The Gloss - Beauty Tips, Trends, And Product Reviews", url: "https://feeds.feedburner.com/intothegloss/oqoU", score: 0.88, category: "beauty" },
    { title: "POPSUGAR Beauty", url: "https://www.popsugar.com/beauty/feed", score: 0.86, category: "beauty" },
    { title: "Refinery29", url: "https://www.refinery29.com/beauty/rss.xml", score: 0.84, category: "beauty" },
    { title: "THE YESSTYLIST – Asian Fashion Blog – brought to you by YesStyle.com", url: "https://www.yesstyle.com/blog/category/the-beauty-blog/feed/", score: 0.82, category: "beauty" },
    { title: "The Beauty Look Book", url: "https://thebeautylookbook.com/feed", score: 0.80, category: "beauty" },
  ],
  "books": [
    { title: "A year of reading the world", url: "https://ayearofreadingtheworld.com/feed/", score: 1.00, category: "books" },
    { title: "Aestas Book Blog", url: "https://aestasbookblog.com/feed/", score: 0.98, category: "books" },
    { title: "BOOK RIOT", url: "https://bookriot.com/feed/", score: 0.96, category: "books" },
    { title: "Kirkus Reviews", url: "https://www.kirkusreviews.com/feeds/rss/", score: 0.94, category: "books" },
    { title: "Page Array – NewInBooks", url: "https://www.newinbooks.com/feed/", score: 0.92, category: "books" },
    { title: "So many books, so little time", url: "https://reddit.com/r/books/.rss", score: 0.90, category: "books" },
    { title: "Wokeread", url: "https://wokeread.home.blog/feed/", score: 0.88, category: "books" },
  ],
  "business-economy": [
    { title: "All News", url: "https://www.investing.com/rss/news.rss", score: 1.00, category: "business-economy" },
    { title: "Bloomberg Quicktake", url: "https://www.youtube.com/feeds/videos.xml?user=Bloomberg", score: 0.98, category: "business-economy" },
    { title: "Breaking News on Seeking Alpha", url: "https://seekingalpha.com/market_currents.xml", score: 0.96, category: "business-economy" },
    { title: "Business Insider", url: "https://www.youtube.com/feeds/videos.xml?user=businessinsider", score: 0.94, category: "business-economy" },
    { title: "Duct Tape Marketing", url: "https://ducttape.libsyn.com/rss", score: 0.92, category: "business-economy" },
    { title: "Economic Times", url: "https://economictimes.indiatimes.com/rssfeedsdefault.cms", score: 0.90, category: "business-economy" },
    { title: "Forbes - Business", url: "https://www.forbes.com/business/feed/", score: 0.88, category: "business-economy" },
    { title: "Fortune", url: "https://fortune.com/feed", score: 0.86, category: "business-economy" },
    { title: "HBR IdeaCast", url: "http://feeds.harvardbusiness.org/harvardbusiness/ideacast", score: 0.84, category: "business-economy" },
    { title: "Home Page", url: "https://www.business-standard.com/rss/home_page_top_stories.rss", score: 0.82, category: "business-economy" },
    { title: "Startup Stories - Mixergy", url: "https://feeds.feedburner.com/Mixergy-main-podcast", score: 0.80, category: "business-economy" },
    { title: "The Blog of Author Tim Ferriss", url: "https://tim.blog/feed/", score: 0.78, category: "business-economy" },
    { title: "The Growth Show", url: "http://thegrowthshow.hubspot.libsynpro.com/", score: 0.76, category: "business-economy" },
    { title: "US Top News and Analysis", url: "https://www.cnbc.com/id/100003114/device/rss/rss.html", score: 0.74, category: "business-economy" },
    { title: "Yahoo Finance", url: "https://finance.yahoo.com/news/rssindex", score: 0.72, category: "business-economy" },
  ],
  "cars": [
    { title: "Autoblog", url: "https://www.autoblog.com/rss.xml", score: 1.00, category: "cars" },
    { title: "Autocar India - All Bike Reviews", url: "https://www.autocarindia.com/RSS/rss.ashx?type=all_bikes", score: 0.98, category: "cars" },
    { title: "Autocar India - All Car Reviews", url: "https://www.autocarindia.com/RSS/rss.ashx?type=all_cars", score: 0.96, category: "cars" },
    { title: "Autocar India - News", url: "https://www.autocarindia.com/RSS/rss.ashx?type=News", score: 0.94, category: "cars" },
    { title: "Autocar RSS Feed", url: "https://www.autocar.co.uk/rss", score: 0.92, category: "cars" },
    { title: "BMW BLOG", url: "https://feeds.feedburner.com/BmwBlog", score: 0.90, category: "cars" },
    { title: "Bike EXIF", url: "https://www.bikeexif.com/feed", score: 0.88, category: "cars" },
    { title: "Car Body Design", url: "https://www.carbodydesign.com/feed/", score: 0.86, category: "cars" },
    { title: "Carscoops", url: "https://www.carscoops.com/feed/", score: 0.84, category: "cars" },
    { title: "Formula 1", url: "https://www.reddit.com/r/formula1/.rss", score: 0.82, category: "cars" },
    { title: "Jalopnik", url: "https://jalopnik.com/rss", score: 0.80, category: "cars" },
    { title: "Latest Content - Car and Driver", url: "https://www.caranddriver.com/rss/all.xml/", score: 0.78, category: "cars" },
    { title: "Petrolicious", url: "https://petrolicious.com/feed", score: 0.76, category: "cars" },
    { title: "Section Page News - Automotive News", url: "http://feeds.feedburner.com/autonews/AutomakerNews", score: 0.74, category: "cars" },
    { title: "Section Page News - Automotive News", url: "http://feeds.feedburner.com/autonews/EditorsPicks", score: 0.72, category: "cars" },
    { title: "Speedhunters", url: "http://feeds.feedburner.com/speedhunters", score: 0.70, category: "cars" },
    { title: "The Truth About Cars", url: "https://www.thetruthaboutcars.com/feed/", score: 0.68, category: "cars" },
    { title: "The best vintage and classic cars for sale online | Bring a Trailer", url: "https://bringatrailer.com/feed/", score: 0.66, category: "cars" },
  ],
  "cricket": [
    { title: "BBC Sport - Cricket", url: "http://feeds.bbci.co.uk/sport/cricket/rss.xml", score: 1.00, category: "cricket" },
    { title: "Can't Bowl Can't Throw Cricket Show", url: "http://feeds.feedburner.com/cantbowlcantthrow", score: 0.98, category: "cricket" },
    { title: "Cricbuzz", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSRQXk5yErn4e14vN76upOw", score: 0.96, category: "cricket" },
    { title: "Cricket", url: "https://www.reddit.com/r/Cricket/.rss", score: 0.94, category: "cricket" },
    { title: "Cricket news from ESPN Cricinfo.com", url: "http://www.espncricinfo.com/rss/content/story/feeds/0.xml", score: 0.92, category: "cricket" },
    { title: "Cricket | The Guardian", url: "https://www.theguardian.com/sport/cricket/rss", score: 0.90, category: "cricket" },
    { title: "Cricket – The Roar", url: "https://www.theroar.com.au/cricket/feed/", score: 0.88, category: "cricket" },
    { title: "England & Wales Cricket Board", url: "https://www.youtube.com/feeds/videos.xml?user=ecbcricket", score: 0.86, category: "cricket" },
    { title: "NDTV Sports - Cricket", url: "http://feeds.feedburner.com/ndtvsports-cricket", score: 0.84, category: "cricket" },
    { title: "Pakistan Cricket", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCiWrjBhlICf_L_RK5y6Vrxw", score: 0.82, category: "cricket" },
    { title: "Sky Sports Cricket Podcast", url: "https://www.spreaker.com/show/3387348/episodes/feed", score: 0.80, category: "cricket" },
    { title: "Sri Lanka Cricket", url: "https://www.youtube.com/feeds/videos.xml?user=TheOfficialSLC", score: 0.78, category: "cricket" },
    { title: "Stumped", url: "https://podcasts.files.bbci.co.uk/p02gsrmh.rss", score: 0.76, category: "cricket" },
    { title: "Switch Hit Podcast", url: "https://feeds.megaphone.fm/ESP9247246951", score: 0.74, category: "cricket" },
    { title: "Tailenders", url: "https://podcasts.files.bbci.co.uk/p02pcb4w.rss", score: 0.72, category: "cricket" },
    { title: "Test Match Special", url: "https://podcasts.files.bbci.co.uk/p02nrsl2.rss", score: 0.70, category: "cricket" },
    { title: "The Grade Cricketer", url: "https://rss.whooshkaa.com/rss/podcast/id/1308", score: 0.68, category: "cricket" },
    { title: "Wisden", url: "https://www.wisden.com/feed", score: 0.66, category: "cricket" },
    { title: "Wisden Cricket Weekly", url: "http://feeds.soundcloud.com/users/soundcloud:users:341034518/sounds.rss", score: 0.64, category: "cricket" },
    { title: "cricket.com.au", url: "https://www.youtube.com/feeds/videos.xml?user=cricketaustraliatv", score: 0.62, category: "cricket" },
  ],
  "interior-design": [
    { title: "Apartment Therapy| Saving the world, one room at a time", url: "https://www.apartmenttherapy.com/design.rss", score: 1.00, category: "interior-design" },
    { title: "Better Living Through Design", url: "http://www.betterlivingthroughdesign.com/feed/", score: 0.98, category: "interior-design" },
    { title: "Core77", url: "http://feeds.feedburner.com/core77/blog", score: 0.96, category: "interior-design" },
    { title: "Design MilkInterior Design – Design Milk", url: "https://design-milk.com/category/interior-design/feed/", score: 0.94, category: "interior-design" },
    { title: "Fubiz Media", url: "http://feeds.feedburner.com/fubiz", score: 0.92, category: "interior-design" },
    { title: "Ideal Home", url: "https://www.idealhome.co.uk/feed", score: 0.90, category: "interior-design" },
    { title: "In My Own Style", url: "https://inmyownstyle.com/feed", score: 0.88, category: "interior-design" },
    { title: "Inhabitat - Green Design, Innovation, Architecture, Green Building", url: "https://inhabitat.com/design/feed/", score: 0.86, category: "interior-design" },
    { title: "Interior Design (Interior Architecture)", url: "https://www.reddit.com/r/InteriorDesign/.rss", score: 0.84, category: "interior-design" },
    { title: "Interior Design Ideas", url: "http://www.home-designing.com/feed", score: 0.82, category: "interior-design" },
    { title: "Interior Design Latest", url: "https://www.interiordesign.net/rss/", score: 0.80, category: "interior-design" },
    { title: "Interiors – Dezeen", url: "https://www.dezeen.com/interiors/feed/", score: 0.78, category: "interior-design" },
    { title: "Liz Marie Blog", url: "https://www.lizmarieblog.com/feed/", score: 0.76, category: "interior-design" },
    { title: "The Design Files | Australia's most popular design blog.The Design Files | Australia's most popular design blog.", url: "https://thedesignfiles.net/feed/", score: 0.74, category: "interior-design" },
    { title: "The Inspired Room", url: "https://theinspiredroom.net/feed/", score: 0.72, category: "interior-design" },
    { title: "Thrifty Decor Chick", url: "http://feeds.feedburner.com/blogspot/ZBcZ", score: 0.70, category: "interior-design" },
    { title: "Trendir", url: "https://www.trendir.com/feed/", score: 0.68, category: "interior-design" },
    { title: "Yanko Design", url: "http://feeds.feedburner.com/yankodesign", score: 0.66, category: "interior-design" },
    { title: "Yatzer RSS Feed", url: "https://www.yatzer.com/rss.xml", score: 0.64, category: "interior-design" },
    { title: "Young House Love", url: "https://www.younghouselove.com/feed/", score: 0.62, category: "interior-design" },
    { title: "decoist", url: "https://www.decoist.com/feed/", score: 0.60, category: "interior-design" },
    { title: "design – designboom | architecture & design magazine", url: "https://www.designboom.com/design/feed", score: 0.58, category: "interior-design" },
    { title: "sfgirlbybay", url: "https://www.sfgirlbybay.com/feed/", score: 0.56, category: "interior-design" },
  ],
  "diy": [
    { title: "A Beautiful Mess", url: "https://abeautifulmess.com/feed", score: 1.00, category: "diy" },
    { title: "Apartment Therapy| Saving the world, one room at a time", url: "https://www.apartmenttherapy.com/projects.rss", score: 0.98, category: "diy" },
    { title: "Blog – Hackaday", url: "https://hackaday.com/blog/feed/", score: 0.96, category: "diy" },
    { title: "Centsational Style", url: "https://centsationalstyle.com/feed/", score: 0.94, category: "diy" },
    { title: "Doityourself.com", url: "https://www.doityourself.com/feed", score: 0.92, category: "diy" },
    { title: "Etsy Journal", url: "https://blog.etsy.com/en/feed/", score: 0.90, category: "diy" },
    { title: "How-To Geek", url: "https://www.howtogeek.com/feed/", score: 0.88, category: "diy" },
    { title: "IKEA Hackers", url: "https://www.ikeahackers.net/feed", score: 0.86, category: "diy" },
    { title: "MUO - Feed", url: "https://www.makeuseof.com/feed/", score: 0.84, category: "diy" },
    { title: "Oh Happy Day!", url: "http://ohhappyday.com/feed/", score: 0.82, category: "diy" },
    { title: "WonderHowTo", url: "https://www.wonderhowto.com/rss.xml", score: 0.80, category: "diy" },
  ],
  "fashion": [
    { title: "Fashion - ELLE", url: "https://www.elle.com/rss/fashion.xml/", score: 1.00, category: "fashion" },
    { title: "Fashion | The Guardian", url: "https://www.theguardian.com/fashion/rss", score: 0.98, category: "fashion" },
    { title: "Fashion – Indian Fashion Blog", url: "https://www.fashionlady.in/category/fashion/feed", score: 0.96, category: "fashion" },
    { title: "FashionBeans Men's Fashion and Style Feed", url: "https://www.fashionbeans.com/rss-feed/?category=fashion", score: 0.94, category: "fashion" },
    { title: "Fashionista", url: "https://fashionista.com/.rss/excerpt/", score: 0.92, category: "fashion" },
    { title: "POPSUGAR Fashion", url: "https://www.popsugar.com/fashion/feed", score: 0.90, category: "fashion" },
    { title: "Refinery29", url: "https://www.refinery29.com/fashion/rss.xml", score: 0.88, category: "fashion" },
    { title: "THE YESSTYLIST – Asian Fashion Blog – brought to you by YesStyle.com", url: "https://www.yesstyle.com/blog/category/trend-and-style/feed/", score: 0.86, category: "fashion" },
    { title: "Who What Wear", url: "https://www.whowhatwear.com/rss", score: 0.84, category: "fashion" },
  ],
  "food": [
    { title: "101 Cookbooks", url: "https://www.101cookbooks.com/feed", score: 1.00, category: "food" },
    { title: "Babish Culinary Universe", url: "https://www.youtube.com/feeds/videos.xml?user=bgfilms", score: 0.98, category: "food" },
    { title: "Bon Appétit", url: "https://www.youtube.com/feeds/videos.xml?user=BonAppetitDotCom", score: 0.96, category: "food" },
    { title: "Chocolate & Zucchini", url: "https://cnz.to/feed/", score: 0.94, category: "food" },
    { title: "David Lebovitz", url: "https://www.davidlebovitz.com/feed/", score: 0.92, category: "food" },
    { title: "Food52", url: "http://feeds.feedburner.com/food52-TheAandMBlog", score: 0.90, category: "food" },
    { title: "Green Kitchen Stories", url: "https://greenkitchenstories.com/feed/", score: 0.88, category: "food" },
    { title: "How Sweet Eats", url: "https://www.howsweeteats.com/feed/", score: 0.86, category: "food" },
    { title: "Joy the Baker", url: "http://joythebaker.com/feed/", score: 0.84, category: "food" },
    { title: "Kitchn | Inspiring cooks, nourishing homes", url: "https://www.thekitchn.com/main.rss", score: 0.82, category: "food" },
    { title: "Laura in the Kitchen", url: "https://www.youtube.com/feeds/videos.xml?user=LauraVitalesKitchen", score: 0.80, category: "food" },
    { title: "Love and Olive Oil", url: "https://www.loveandoliveoil.com/feed", score: 0.78, category: "food" },
    { title: "Oh She Glows", url: "https://ohsheglows.com/feed/", score: 0.76, category: "food" },
    { title: "Serious Eats", url: "https://www.youtube.com/feeds/videos.xml?user=SeriousEats", score: 0.74, category: "food" },
    { title: "Serious Eats: Recipes", url: "http://feeds.feedburner.com/seriouseats/recipes", score: 0.72, category: "food" },
    { title: "Shutterbean", url: "http://www.shutterbean.com/feed/", score: 0.70, category: "food" },
    { title: "Skinnytaste", url: "https://www.skinnytaste.com/feed/", score: 0.68, category: "food" },
    { title: "Sprouted Kitchen", url: "https://www.sproutedkitchen.com/home?format=rss", score: 0.66, category: "food" },
    { title: "Williams-Sonoma Taste", url: "https://blog.williams-sonoma.com/feed/", score: 0.64, category: "food" },
    { title: "smitten kitchen", url: "http://feeds.feedburner.com/smittenkitchen", score: 0.62, category: "food" },
  ],
  "football": [
    { title: "EFL Championship", url: "https://www.reddit.com/r/Championship/.rss?format=xml", score: 1.00, category: "football" },
    { title: "Football - The People's Sport", url: "https://www.reddit.com/r/football/.rss?format=xml", score: 0.98, category: "football" },
    { title: "Football News, Live Scores, Results & Transfers | Goal.com", url: "https://www.goal.com/feeds/en/news", score: 0.96, category: "football" },
    { title: "Football365", url: "https://www.football365.com/feed", score: 0.94, category: "football" },
    { title: "Soccer News", url: "https://www.soccernews.com/feed", score: 0.92, category: "football" },
  ],
  "funny": [
    { title: "AwkwardFamilyPhotos.com", url: "https://awkwardfamilyphotos.com/feed/", score: 1.00, category: "funny" },
    { title: "Cracked: All Posts", url: "http://feeds.feedburner.com/CrackedRSS", score: 0.98, category: "funny" },
    { title: "Explosm.net", url: "http://feeds.feedburner.com/Explosm", score: 0.96, category: "funny" },
    { title: "FAIL Blog", url: "http://feeds.feedburner.com/failblog", score: 0.94, category: "funny" },
    { title: "I Can Has Cheezburger?", url: "http://feeds.feedburner.com/icanhascheezburger", score: 0.92, category: "funny" },
    { title: "PHD Comics", url: "http://phdcomics.com/gradfeed.php", score: 0.90, category: "funny" },
    { title: "Penny Arcade", url: "https://www.penny-arcade.com/feed", score: 0.88, category: "funny" },
    { title: "PostSecret", url: "https://postsecret.com/feed/?alt=rss", score: 0.86, category: "funny" },
    { title: "Saturday Morning Breakfast Cereal", url: "https://www.smbc-comics.com/comic/rss", score: 0.84, category: "funny" },
    { title: "The Bloggess", url: "https://thebloggess.com/feed/", score: 0.82, category: "funny" },
    { title: "The Daily WTF", url: "http://syndication.thedailywtf.com/TheDailyWtf", score: 0.80, category: "funny" },
    { title: "The Oatmeal - Comics by Matthew Inman", url: "http://feeds.feedburner.com/oatmealfeed", score: 0.78, category: "funny" },
    { title: "The Onion", url: "https://www.theonion.com/rss", score: 0.76, category: "funny" },
    { title: "xkcd.com", url: "https://xkcd.com/rss.xml", score: 0.74, category: "funny" },
  ],
  "gaming": [
    { title: "Escapist Magazine", url: "https://www.escapistmagazine.com/v2/feed/", score: 1.00, category: "gaming" },
    { title: "Eurogamer.net", url: "https://www.eurogamer.net/?format=rss", score: 0.98, category: "gaming" },
    { title: "Gamasutra News", url: "http://feeds.feedburner.com/GamasutraNews", score: 0.96, category: "gaming" },
    { title: "GameSpot - All Content", url: "https://www.gamespot.com/feeds/mashup/", score: 0.94, category: "gaming" },
    { title: "IGN All", url: "http://feeds.ign.com/ign/all", score: 0.92, category: "gaming" },
    { title: "Indie Games Plus", url: "https://indiegamesplus.com/feed", score: 0.90, category: "gaming" },
    { title: "Kotaku", url: "https://kotaku.com/rss", score: 0.88, category: "gaming" },
    { title: "Makeup and Beauty Blog | Makeup Reviews, Swatches and How-To Makeup", url: "https://www.makeupandbeautyblog.com/feed/", score: 0.86, category: "gaming" },
    { title: "PlayStation.Blog", url: "http://feeds.feedburner.com/psblog", score: 0.84, category: "gaming" },
    { title: "Polygon -  All", url: "https://www.polygon.com/rss/index.xml", score: 0.82, category: "gaming" },
    { title: "Rock, Paper, Shotgun", url: "http://feeds.feedburner.com/RockPaperShotgun", score: 0.80, category: "gaming" },
    { title: "Steam RSS News Feed", url: "https://store.steampowered.com/feeds/news.xml", score: 0.78, category: "gaming" },
    { title: "The Ancient Gaming Noob", url: "http://feeds.feedburner.com/TheAncientGamingNoob", score: 0.76, category: "gaming" },
    { title: "TouchArcade - iPhone, iPad, Android Games Forum", url: "https://toucharcade.com/community/forums/-/index.rss", score: 0.74, category: "gaming" },
    { title: "Xbox's Major Nelson", url: "https://majornelson.com/feed/", score: 0.72, category: "gaming" },
    { title: "r/gaming", url: "https://www.reddit.com/r/gaming.rss", score: 0.70, category: "gaming" },
  ],
  "history": [
    { title: "30 For 30 Podcasts", url: "https://feeds.megaphone.fm/ESP5765452710", score: 1.00, category: "history" },
    { title: "Blog Feed", url: "https://americanhistory.si.edu/blog/feed", score: 0.98, category: "history" },
    { title: "Dan Carlin's Hardcore History", url: "https://feeds.feedburner.com/dancarlin/history?format=xml", score: 0.96, category: "history" },
    { title: "History in 28-minutes", url: "https://www.historyisnowmagazine.com/blog?format=RSS", score: 0.94, category: "history" },
    { title: "HistoryNet", url: "http://www.historynet.com/feed", score: 0.92, category: "history" },
    { title: "Lore", url: "https://feeds.megaphone.fm/lore", score: 0.90, category: "history" },
    { title: "Revisionist History", url: "https://feeds.megaphone.fm/revisionisthistory", score: 0.88, category: "history" },
    { title: "The History Reader", url: "https://www.thehistoryreader.com/feed/", score: 0.86, category: "history" },
    { title: "Throughline", url: "https://feeds.npr.org/510333/podcast.xml", score: 0.84, category: "history" },
    { title: "You Must Remember This", url: "https://feeds.megaphone.fm/YMRT7068253588", score: 0.82, category: "history" },
  ],
  "ios-development": [
    { title: "ALL SHOWS - Devchat.tv", url: "https://feeds.feedwrench.com/all-shows-devchattv.rss", score: 1.00, category: "ios-development" },
    { title: "Alberto De Bortoli", url: "https://albertodebortoli.com/rss/", score: 0.98, category: "ios-development" },
    { title: "Augmented Code", url: "https://augmentedcode.io/feed/", score: 0.96, category: "ios-development" },
    { title: "Benoit Pasquier - Swift, Data and more", url: "https://benoitpasquier.com/index.xml", score: 0.94, category: "ios-development" },
    { title: "Fabisevi.ch", url: "https://www.fabisevi.ch/feed.xml", score: 0.92, category: "ios-development" },
    { title: "Mobile A11y", url: "https://mobilea11y.com/index.xml", score: 0.90, category: "ios-development" },
    { title: "More Than Just Code podcast - iOS and Swift development, news and advice", url: "https://feeds.fireside.fm/mtjc/rss", score: 0.88, category: "ios-development" },
    { title: "News - Apple Developer", url: "https://developer.apple.com/news/rss/news.rss", score: 0.86, category: "ios-development" },
    { title: "Ole Begemann", url: "https://oleb.net/blog/atom.xml", score: 0.84, category: "ios-development" },
    { title: "Pavel Zak’s dev blog", url: "https://nerdyak.tech/feed.xml", score: 0.82, category: "ios-development" },
    { title: "Swift by Sundell", url: "https://www.swiftbysundell.com/feed.rss", score: 0.80, category: "ios-development" },
    { title: "Swift by Sundell", url: "https://swiftbysundell.com/feed.rss", score: 0.78, category: "ios-development" },
    { title: "SwiftRocks", url: "https://swiftrocks.com/rss.xml", score: 0.76, category: "ios-development" },
    { title: "The Atomic Birdhouse", url: "https://atomicbird.com/index.xml", score: 0.74, category: "ios-development" },
    { title: "Under the Radar", url: "https://www.relay.fm/radar/feed", score: 0.72, category: "ios-development" },
    { title: "Use Your Loaf - iOS Development News & Tips", url: "https://useyourloaf.com/blog/rss.xml", score: 0.70, category: "ios-development" },
    { title: "inessential.com", url: "https://inessential.com/xml/rss.xml", score: 0.68, category: "ios-development" },
    { title: "tyler.io", url: "https://tyler.io/feed/", score: 0.66, category: "ios-development" },
  ],
  "movies": [
    { title: "/Film", url: "https://feeds2.feedburner.com/slashfilm", score: 1.00, category: "movies" },
    { title: "Ain't It Cool News Feed", url: "https://www.aintitcool.com/node/feed/", score: 0.98, category: "movies" },
    { title: "ComingSoon.net", url: "https://www.comingsoon.net/feed", score: 0.96, category: "movies" },
    { title: "Deadline", url: "https://deadline.com/feed/", score: 0.94, category: "movies" },
    { title: "Film School Rejects", url: "https://filmschoolrejects.com/feed/", score: 0.92, category: "movies" },
    { title: "FirstShowing.net", url: "https://www.firstshowing.net/feed/", score: 0.90, category: "movies" },
    { title: "IndieWire", url: "https://www.indiewire.com/feed", score: 0.88, category: "movies" },
    { title: "Movie News and Discussion", url: "https://reddit.com/r/movies/.rss", score: 0.86, category: "movies" },
    { title: "Movies", url: "https://www.bleedingcool.com/movies/feed/", score: 0.84, category: "movies" },
    { title: "The A.V. Club", url: "https://film.avclub.com/rss", score: 0.82, category: "movies" },
    { title: "Variety", url: "https://variety.com/feed/", score: 0.80, category: "movies" },
  ],
  "music": [
    { title: "Billboard", url: "https://www.billboard.com/articles/rss.xml", score: 1.00, category: "music" },
    { title: "Consequence", url: "http://consequenceofsound.net/feed", score: 0.98, category: "music" },
    { title: "EDM.com - The Latest Electronic Dance Music News, Reviews & Artists", url: "https://edm.com/.rss/full/", score: 0.96, category: "music" },
    { title: "Metal Injection", url: "http://feeds.feedburner.com/metalinjection", score: 0.94, category: "music" },
    { title: "Music Business Worldwide", url: "https://www.musicbusinessworldwide.com/feed/", score: 0.92, category: "music" },
    { title: "RSS: News", url: "http://pitchfork.com/rss/news", score: 0.90, category: "music" },
    { title: "Song Exploder", url: "http://songexploder.net/feed", score: 0.88, category: "music" },
    { title: "Your EDM", url: "https://www.youredm.com/feed", score: 0.86, category: "music" },
  ],
  "news": [
    { title: "BBC News - World", url: "http://feeds.bbci.co.uk/news/world/rss.xml", score: 1.00, category: "news" },
    { title: "CNN.com - RSS Channel - World", url: "http://rss.cnn.com/rss/edition_world.rss", score: 0.98, category: "news" },
    { title: "International: Top News And Analysis", url: "https://www.cnbc.com/id/100727362/device/rss/rss.html", score: 0.96, category: "news" },
    { title: "NDTV News - World-news", url: "http://feeds.feedburner.com/ndtvnews-world-news", score: 0.94, category: "news" },
    { title: "Top stories - Google News", url: "https://news.google.com/rss", score: 0.92, category: "news" },
    { title: "World", url: "http://feeds.washingtonpost.com/rss/world", score: 0.90, category: "news" },
    { title: "World News", url: "https://www.reddit.com/r/worldnews/.rss", score: 0.88, category: "news" },
    { title: "World News Headlines, Latest International News, World Breaking News - Times of India", url: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms", score: 0.86, category: "news" },
    { title: "World news | The Guardian", url: "https://www.theguardian.com/world/rss", score: 0.84, category: "news" },
    { title: "Yahoo News - Latest News & Headlines", url: "https://www.yahoo.com/news/rss", score: 0.82, category: "news" },
  ],
  "personal-finance": [
    { title: "Afford Anything", url: "https://affordanything.com/feed/", score: 1.00, category: "personal-finance" },
    { title: "Blog – Student Loan Hero", url: "https://studentloanhero.com/blog/feed", score: 0.98, category: "personal-finance" },
    { title: "Budgets Are Sexy", url: "https://feeds2.feedburner.com/budgetsaresexy", score: 0.96, category: "personal-finance" },
    { title: "Financial Samurai", url: "https://www.financialsamurai.com/feed/", score: 0.94, category: "personal-finance" },
    { title: "Frugalwoods", url: "https://feeds.feedburner.com/Frugalwoods", score: 0.92, category: "personal-finance" },
    { title: "Get Rich Slowly", url: "https://www.getrichslowly.org/feed/", score: 0.90, category: "personal-finance" },
    { title: "Good Financial Cents®", url: "https://www.goodfinancialcents.com/feed/", score: 0.88, category: "personal-finance" },
    { title: "I Will Teach You To Be Rich", url: "https://www.iwillteachyoutoberich.com/feed/", score: 0.86, category: "personal-finance" },
    { title: "Learn To Trade The Market", url: "https://www.learntotradethemarket.com/feed", score: 0.84, category: "personal-finance" },
    { title: "Making Sense Of Cents", url: "https://www.makingsenseofcents.com/feed", score: 0.82, category: "personal-finance" },
    { title: "Millennial Money", url: "https://millennialmoney.com/feed/", score: 0.80, category: "personal-finance" },
    { title: "MintLife Blog", url: "https://blog.mint.com/feed/", score: 0.78, category: "personal-finance" },
    { title: "Money Crashers", url: "https://www.moneycrashers.com/feed/", score: 0.76, category: "personal-finance" },
    { title: "Money Saving Mom®", url: "https://moneysavingmom.com/feed/", score: 0.74, category: "personal-finance" },
    { title: "Money Under 30", url: "https://www.moneyunder30.com/feed", score: 0.72, category: "personal-finance" },
    { title: "MoneyNing", url: "http://feeds.feedburner.com/MoneyNing", score: 0.70, category: "personal-finance" },
    { title: "MyWifeQuitHerJob.com", url: "https://mywifequitherjob.com/feed/", score: 0.68, category: "personal-finance" },
    { title: "Nerd's Eye View | Kitces.com", url: "http://feeds.feedblitz.com/kitcesnerdseyeview&x=1", score: 0.66, category: "personal-finance" },
    { title: "NerdWallet", url: "https://www.nerdwallet.com/blog/feed/", score: 0.64, category: "personal-finance" },
    { title: "Oblivious Investor", url: "https://obliviousinvestor.com/feed/", score: 0.62, category: "personal-finance" },
    { title: "Personal Finance", url: "https://reddit.com/r/personalfinance/.rss", score: 0.60, category: "personal-finance" },
    { title: "SavingAdvice.com Blog", url: "https://www.savingadvice.com/feed/", score: 0.58, category: "personal-finance" },
    { title: "Side Hustle Nation", url: "https://www.sidehustlenation.com/feed", score: 0.56, category: "personal-finance" },
    { title: "The College Investor", url: "https://thecollegeinvestor.com/feed/", score: 0.54, category: "personal-finance" },
    { title: "The Dough Roller", url: "https://www.doughroller.net/feed/", score: 0.52, category: "personal-finance" },
    { title: "The Penny Hoarder", url: "https://www.thepennyhoarder.com/feed/", score: 0.50, category: "personal-finance" },
    { title: "Well Kept Wallet", url: "https://wellkeptwallet.com/feed/", score: 0.50, category: "personal-finance" },
    { title: "Wise Bread", url: "http://feeds.killeraces.com/wisebread", score: 0.50, category: "personal-finance" },
  ],
  "photography": [
    { title: "500px", url: "https://iso.500px.com/feed/", score: 1.00, category: "photography" },
    { title: "500px:", url: "https://500px.com/editors.rss", score: 0.98, category: "photography" },
    { title: "Big Picture", url: "https://www.bostonglobe.com/rss/bigpicture", score: 0.96, category: "photography" },
    { title: "Canon Rumors – Your best source for Canon rumors, leaks and gossip", url: "https://www.canonrumors.com/feed/", score: 0.94, category: "photography" },
    { title: "Digital Photography School", url: "https://feeds.feedburner.com/DigitalPhotographySchool", score: 0.92, category: "photography" },
    { title: "Light Stalking", url: "https://www.lightstalking.com/feed/", score: 0.90, category: "photography" },
    { title: "Lightroom Killer Tips", url: "https://lightroomkillertips.com/feed/", score: 0.88, category: "photography" },
    { title: "One Big Photo", url: "http://feeds.feedburner.com/OneBigPhoto", score: 0.86, category: "photography" },
    { title: "PetaPixel", url: "https://petapixel.com/feed/", score: 0.84, category: "photography" },
    { title: "Strobist", url: "http://feeds.feedburner.com/blogspot/WOBq", score: 0.82, category: "photography" },
    { title: "Stuck in Customs", url: "https://stuckincustoms.com/feed/", score: 0.80, category: "photography" },
    { title: "The Sartorialist", url: "https://feeds.feedburner.com/TheSartorialist", score: 0.78, category: "photography" },
  ],
  "programming": [
    { title: "Better Programming - Medium", url: "https://medium.com/feed/better-programming", score: 1.00, category: "programming" },
    { title: "Code as Craft", url: "https://codeascraft.com/feed/atom/", score: 0.98, category: "programming" },
    { title: "CodeNewbie", url: "http://feeds.codenewbie.org/cnpodcast.xml", score: 0.96, category: "programming" },
    { title: "Coding Horror", url: "https://feeds.feedburner.com/codinghorror", score: 0.94, category: "programming" },
    { title: "Complete Developer Podcast", url: "https://completedeveloperpodcast.com/feed/podcast/", score: 0.92, category: "programming" },
    { title: "Dan Abramov's Overreacted Blog RSS Feed", url: "https://overreacted.io/rss.xml", score: 0.90, category: "programming" },
    { title: "Developer Tea", url: "https://feeds.simplecast.com/dLRotFGk", score: 0.88, category: "programming" },
    { title: "English (US)", url: "https://blog.twitter.com/engineering/en_us/blog.rss", score: 0.86, category: "programming" },
    { title: "FLOSS Weekly (Audio)", url: "https://feeds.twit.tv/floss.xml", score: 0.84, category: "programming" },
    { title: "Facebook Engineering", url: "https://engineering.fb.com/feed/", score: 0.82, category: "programming" },
    { title: "GitLab", url: "https://about.gitlab.com/atom.xml", score: 0.80, category: "programming" },
    { title: "Google Developers Blog", url: "http://feeds.feedburner.com/GDBcode", score: 0.78, category: "programming" },
    { title: "Google TechTalks", url: "https://www.youtube.com/feeds/videos.xml?user=GoogleTechTalks", score: 0.76, category: "programming" },
    { title: "HackerNoon.com - Medium", url: "https://medium.com/feed/hackernoon", score: 0.74, category: "programming" },
    { title: "Hanselminutes with Scott Hanselman", url: "https://feeds.simplecast.com/gvtxUiIf", score: 0.72, category: "programming" },
    { title: "InfoQ", url: "https://feed.infoq.com", score: 0.70, category: "programming" },
    { title: "Instagram Engineering - Medium", url: "https://instagram-engineering.com/feed/", score: 0.68, category: "programming" },
    { title: "Java, SQL and jOOQ.", url: "https://blog.jooq.org/feed", score: 0.66, category: "programming" },
    { title: "JetBrains Blog", url: "https://blog.jetbrains.com/feed", score: 0.64, category: "programming" },
    { title: "Joel on Software", url: "https://www.joelonsoftware.com/feed/", score: 0.62, category: "programming" },
    { title: "LinkedIn Engineering", url: "https://engineering.linkedin.com/blog.rss.html", score: 0.60, category: "programming" },
    { title: "Martin Fowler", url: "https://martinfowler.com/feed.atom", score: 0.58, category: "programming" },
    { title: "Netflix TechBlog - Medium", url: "https://netflixtechblog.com/feed", score: 0.56, category: "programming" },
    { title: "Overflow - Buffer Resources", url: "https://buffer.com/resources/overflow/rss/", score: 0.54, category: "programming" },
    { title: "Podcast – Software Engineering Daily", url: "https://softwareengineeringdaily.com/category/podcast/feed", score: 0.52, category: "programming" },
    { title: "Prezi Engineering - Medium", url: "https://engineering.prezi.com/feed", score: 0.50, category: "programming" },
    { title: "Programming Throwdown", url: "http://feeds.feedburner.com/ProgrammingThrowdown", score: 0.50, category: "programming" },
    { title: "Programming – The Crazy Programmer", url: "https://www.thecrazyprogrammer.com/category/programming/feed", score: 0.50, category: "programming" },
    { title: "Robert Heaton | Blog", url: "https://robertheaton.com/feed.xml", score: 0.50, category: "programming" },
    { title: "Scott Hanselman's Blog", url: "http://feeds.hanselman.com/ScottHanselman", score: 0.50, category: "programming" },
    { title: "Scripting News", url: "http://scripting.com/rss.xml", score: 0.50, category: "programming" },
    { title: "Slack Engineering", url: "https://slack.engineering/feed", score: 0.50, category: "programming" },
    { title: "Software Defined Talk", url: "https://feeds.fireside.fm/sdt/rss", score: 0.50, category: "programming" },
    { title: "Software Engineering Radio - The Podcast for Professional Software Developers", url: "http://feeds.feedburner.com/se-radio", score: 0.50, category: "programming" },
    { title: "SoundCloud Backstage Blog", url: "https://developers.soundcloud.com/blog/blog.rss", score: 0.50, category: "programming" },
    { title: "Spotify Engineering", url: "https://labs.spotify.com/feed/", score: 0.50, category: "programming" },
    { title: "Stack Abuse", url: "https://stackabuse.com/rss/", score: 0.50, category: "programming" },
    { title: "Stack Overflow Blog", url: "https://stackoverflow.blog/feed/", score: 0.50, category: "programming" },
    { title: "The 6 Figure Developer", url: "http://6figuredev.com/feed/rss/", score: 0.50, category: "programming" },
    { title: "The Airbnb Tech Blog - Medium", url: "https://medium.com/feed/airbnb-engineering", score: 0.50, category: "programming" },
    { title: "The Cynical Developer", url: "https://cynicaldeveloper.com/feed/podcast", score: 0.50, category: "programming" },
    { title: "The GitHub Blog", url: "https://github.blog/feed/", score: 0.50, category: "programming" },
    { title: "The PIT Show: Reflections and Interviews in the Tech World", url: "https://feeds.transistor.fm/productivity-in-tech-podcast", score: 0.50, category: "programming" },
    { title: "The Rabbit Hole: The Definitive Developer's Podcast", url: "http://therabbithole.libsyn.com/rss", score: 0.50, category: "programming" },
    { title: "The Stack Overflow Podcast", url: "https://feeds.simplecast.com/XA_851k3", score: 0.50, category: "programming" },
    { title: "The Standup", url: "https://feeds.fireside.fm/standup/rss", score: 0.50, category: "programming" },
    { title: "The Women in Tech Show: A Technical Podcast", url: "https://thewomenintechshow.com/category/podcast/feed/", score: 0.50, category: "programming" },
    { title: "programming", url: "https://www.reddit.com/r/programming/.rss", score: 0.50, category: "programming" },
  ],
  "science": [
    { title: "60-Second Science", url: "http://rss.sciam.com/sciam/60secsciencepodcast", score: 1.00, category: "science" },
    { title: "BBC News - Science & Environment", url: "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml", score: 0.98, category: "science" },
    { title: "Discovery", url: "https://podcasts.files.bbci.co.uk/p002w557.rss", score: 0.96, category: "science" },
    { title: "FlowingData", url: "https://flowingdata.com/feed", score: 0.94, category: "science" },
    { title: "Gizmodo", url: "https://gizmodo.com/tag/science/rss", score: 0.92, category: "science" },
    { title: "Hidden Brain", url: "https://feeds.npr.org/510308/podcast.xml", score: 0.90, category: "science" },
    { title: "Invisibilia", url: "https://feeds.npr.org/510307/podcast.xml", score: 0.88, category: "science" },
    { title: "Latest Science News -- ScienceDaily", url: "https://www.sciencedaily.com/rss/all.xml", score: 0.86, category: "science" },
    { title: "Nature", url: "https://www.nature.com/nature.rss", score: 0.84, category: "science" },
    { title: "Phys.org - latest science and technology news stories", url: "https://phys.org/rss-feed/", score: 0.82, category: "science" },
    { title: "Probably Science", url: "https://probablyscience.libsyn.com/rss", score: 0.80, category: "science" },
    { title: "Radiolab", url: "http://feeds.wnyc.org/radiolab", score: 0.78, category: "science" },
    { title: "Reddit Science", url: "https://reddit.com/r/science/.rss", score: 0.76, category: "science" },
    { title: "Sawbones: A Marital Tour of Misguided Medicine", url: "https://feeds.simplecast.com/y1LF_sn2", score: 0.74, category: "science" },
    { title: "Science Latest", url: "https://www.wired.com/feed/category/science/latest/rss", score: 0.72, category: "science" },
    { title: "Science Vs", url: "http://feeds.gimletmedia.com/ScienceVs", score: 0.70, category: "science" },
    { title: "Science-Based Medicine", url: "https://sciencebasedmedicine.org/feed/", score: 0.68, category: "science" },
    { title: "Scientific American Content: Global", url: "http://rss.sciam.com/ScientificAmerican-Global", score: 0.66, category: "science" },
    { title: "Shirtloads of Science", url: "https://shirtloadsofscience.libsyn.com/rss", score: 0.64, category: "science" },
    { title: "TED Talks Daily (SD video)", url: "https://pa.tedcdn.com/feeds/talks.rss", score: 0.62, category: "science" },
    { title: "The Infinite Monkey Cage", url: "https://podcasts.files.bbci.co.uk/b00snr0w.rss", score: 0.60, category: "science" },
    { title: "This Week in Science – The Kickass Science Podcast", url: "http://www.twis.org/feed/", score: 0.58, category: "science" },
  ],
  "space": [
    { title: "/r/space: news, articles and discussion", url: "https://www.reddit.com/r/space/.rss?format=xml", score: 1.00, category: "space" },
    { title: "NASA Breaking News", url: "https://www.nasa.gov/rss/dyn/breaking_news.rss", score: 0.98, category: "space" },
    { title: "New Scientist - Space", url: "https://www.newscientist.com/subject/space/feed/", score: 0.96, category: "space" },
    { title: "Sky & Telescope", url: "https://www.skyandtelescope.com/feed/", score: 0.94, category: "space" },
    { title: "Space | The Guardian", url: "https://www.theguardian.com/science/space/rss", score: 0.92, category: "space" },
    { title: "Space.com", url: "https://www.space.com/feeds/all", score: 0.90, category: "space" },
    { title: "SpaceX", url: "https://www.youtube.com/feeds/videos.xml?user=spacexchannel", score: 0.88, category: "space" },
  ],
  "sports": [
    { title: "BBC Sport - Sport", url: "http://feeds.bbci.co.uk/sport/rss.xml", score: 1.00, category: "sports" },
    { title: "Reddit Sports", url: "https://www.reddit.com/r/sports.rss", score: 0.98, category: "sports" },
    { title: "Sports News - Latest Sports and Football News | Sky News", url: "http://feeds.skynews.com/feeds/rss/sports.xml", score: 0.96, category: "sports" },
    { title: "Sportskeeda", url: "https://www.sportskeeda.com/feed", score: 0.94, category: "sports" },
    { title: "Yahoo! Sports - News, Scores, Standings, Rumors, Fantasy Games", url: "https://sports.yahoo.com/rss/", score: 0.92, category: "sports" },
    { title: "www.espn.com - TOP", url: "https://www.espn.com/espn/rss/news", score: 0.90, category: "sports" },
  ],
  "startups": [
    { title: "AVC", url: "https://avc.com/feed/", score: 1.00, category: "startups" },
    { title: "Both Sides of the Table - Medium", url: "https://bothsidesofthetable.com/feed", score: 0.98, category: "startups" },
    { title: "Entrepreneur", url: "http://feeds.feedburner.com/entrepreneur/latest", score: 0.96, category: "startups" },
    { title: "Feld Thoughts", url: "https://feld.com/feed", score: 0.94, category: "startups" },
    { title: "Forbes - Entrepreneurs", url: "https://www.forbes.com/entrepreneurs/feed/", score: 0.92, category: "startups" },
    { title: "GaryVee", url: "https://www.youtube.com/feeds/videos.xml?user=GaryVaynerchuk", score: 0.90, category: "startups" },
    { title: "Hacker News: Front Page", url: "https://hnrss.org/frontpage", score: 0.88, category: "startups" },
    { title: "Inc.com", url: "https://www.inc.com/rss/", score: 0.86, category: "startups" },
    { title: "Inside Intercom", url: "https://www.intercom.com/blog/feed", score: 0.84, category: "startups" },
    { title: "Marie Forleo", url: "https://www.youtube.com/feeds/videos.xml?user=marieforleo", score: 0.82, category: "startups" },
    { title: "Paul Graham: Essays", url: "http://www.aaronsw.com/2002/feeds/pgessays.rss", score: 0.80, category: "startups" },
    { title: "Product Hunt — The best new products, every day", url: "https://www.producthunt.com/feed", score: 0.78, category: "startups" },
    { title: "Quick Sprout", url: "https://www.quicksprout.com/rss", score: 0.76, category: "startups" },
    { title: "Small Business Trends", url: "https://feeds2.feedburner.com/SmallBusinessTrends", score: 0.74, category: "startups" },
    { title: "Smart Passive Income", url: "http://feeds.feedburner.com/smartpassiveincome", score: 0.72, category: "startups" },
    { title: "Springwise", url: "https://www.springwise.com/feed", score: 0.70, category: "startups" },
    { title: "Steve Blank", url: "https://steveblank.com/feed/", score: 0.68, category: "startups" },
    { title: "The Startup Junkies Podcast", url: "https://startupjunkie.libsyn.com/rss", score: 0.66, category: "startups" },
    { title: "The Tim Ferriss Show", url: "https://rss.art19.com/tim-ferriss-show", score: 0.64, category: "startups" },
    { title: "This Week in Startups - Video", url: "http://feeds.feedburner.com/twistvid", score: 0.62, category: "startups" },
    { title: "VentureBeat", url: "https://feeds.feedburner.com/venturebeat/SZYF", score: 0.60, category: "startups" },
    { title: "blog – Feld Thoughts", url: "https://feld.com/archives/tag/blog/feed", score: 0.58, category: "startups" },
  ],
  "tech": [
    { title: "Accidental Tech Podcast", url: "https://atp.fm/rss", score: 1.00, category: "tech" },
    { title: "Analog(ue)", url: "https://www.relay.fm/analogue/feed", score: 0.98, category: "tech" },
    { title: "Ars Technica", url: "http://feeds.arstechnica.com/arstechnica/index", score: 0.96, category: "tech" },
    { title: "CNET", url: "https://www.youtube.com/feeds/videos.xml?user=CNETTV", score: 0.94, category: "tech" },
    { title: "CNET News", url: "https://www.cnet.com/rss/news/", score: 0.92, category: "tech" },
    { title: "Clockwise", url: "https://www.relay.fm/clockwise/feed", score: 0.90, category: "tech" },
    { title: "Gizmodo", url: "https://gizmodo.com/rss", score: 0.88, category: "tech" },
    { title: "Hacker News", url: "https://news.ycombinator.com/rss", score: 0.86, category: "tech" },
    { title: "Lifehacker", url: "https://lifehacker.com/rss", score: 0.84, category: "tech" },
    { title: "Linus Tech Tips", url: "https://www.youtube.com/feeds/videos.xml?user=LinusTechTips", score: 0.82, category: "tech" },
    { title: "Marques Brownlee", url: "https://www.youtube.com/feeds/videos.xml?user=marquesbrownlee", score: 0.80, category: "tech" },
    { title: "Mashable", url: "http://feeds.mashable.com/Mashable", score: 0.78, category: "tech" },
    { title: "ReadWrite", url: "https://readwrite.com/feed/", score: 0.76, category: "tech" },
    { title: "Reply All", url: "https://feeds.megaphone.fm/replyall", score: 0.74, category: "tech" },
    { title: "Rocket", url: "https://www.relay.fm/rocket/feed", score: 0.72, category: "tech" },
    { title: "Slashdot", url: "http://rss.slashdot.org/Slashdot/slashdotMain", score: 0.70, category: "tech" },
    { title: "Stratechery by Ben Thompson", url: "http://stratechery.com/feed/", score: 0.68, category: "tech" },
    { title: "TechCrunch", url: "http://feeds.feedburner.com/TechCrunch", score: 0.66, category: "tech" },
    { title: "The Keyword", url: "https://www.blog.google/rss/", score: 0.64, category: "tech" },
    { title: "The Next Web", url: "https://thenextweb.com/feed/", score: 0.62, category: "tech" },
    { title: "The Verge", url: "https://www.youtube.com/feeds/videos.xml?user=TheVerge", score: 0.60, category: "tech" },
    { title: "The Verge -  All Posts", url: "https://www.theverge.com/rss/index.xml", score: 0.58, category: "tech" },
    { title: "The Vergecast", url: "https://feeds.megaphone.fm/vergecast", score: 0.56, category: "tech" },
    { title: "This Week in Tech (Audio)", url: "https://feeds.twit.tv/twit.xml", score: 0.54, category: "tech" },
    { title: "Unbox Therapy", url: "https://www.youtube.com/feeds/videos.xml?user=unboxtherapy", score: 0.52, category: "tech" },
    { title: "https://www.engadget.com/", url: "https://www.engadget.com/rss.xml", score: 0.50, category: "tech" },
  ],
  "television": [
    { title: "TV", url: "https://www.bleedingcool.com/tv/feed/", score: 1.00, category: "television" },
    { title: "TV Fanatic", url: "https://www.tvfanatic.com/rss.xml", score: 0.98, category: "television" },
    { title: "TVLine", url: "https://tvline.com/feed/", score: 0.96, category: "television" },
    { title: "Television News and Discussion", url: "https://reddit.com/r/television/.rss", score: 0.94, category: "television" },
    { title: "The A.V. Club", url: "https://tv.avclub.com/rss", score: 0.92, category: "television" },
    { title: "the TV addict", url: "http://feeds.feedburner.com/thetvaddict/AXob", score: 0.90, category: "television" },
  ],
  "tennis": [
    { title: "BBC Sport - Tennis", url: "http://feeds.bbci.co.uk/sport/tennis/rss.xml", score: 1.00, category: "tennis" },
    { title: "Essential Tennis Podcast - Instruction, Lessons, Tips", url: "https://feed.podbean.com/essentialtennis/feed.xml", score: 0.98, category: "tennis" },
    { title: "Grand Slam Fantasy Tennis", url: "http://www.grandslamfantasytennis.com/feed/?x=1", score: 0.96, category: "tennis" },
    { title: "Tennis - ATP World Tour", url: "https://www.atptour.com/en/media/rss-feed/xml-feed", score: 0.94, category: "tennis" },
    { title: "Tennis News & Discussion", url: "https://www.reddit.com/r/tennis/.rss", score: 0.92, category: "tennis" },
    { title: "peRFect Tennis", url: "https://www.perfect-tennis.com/feed/", score: 0.90, category: "tennis" },
    { title: "www.espn.com - TENNIS", url: "https://www.espn.com/espn/rss/tennis/news", score: 0.88, category: "tennis" },
  ],
  "travel": [
    { title: "Atlas Obscura - Latest Articles and Places", url: "https://www.atlasobscura.com/feeds/latest", score: 1.00, category: "travel" },
    { title: "Live Life Travel", url: "https://www.livelifetravel.world/feed/", score: 0.98, category: "travel" },
    { title: "Lonely Planet Travel News", url: "https://www.lonelyplanet.com/news/feed/atom/", score: 0.96, category: "travel" },
    { title: "Nomadic Matt's Travel Site", url: "https://www.nomadicmatt.com/travel-blog/feed/", score: 0.94, category: "travel" },
    { title: "Travel | The Guardian", url: "https://www.theguardian.com/uk/travel/rss", score: 0.92, category: "travel" },
  ],
  "ui-ux": [
    { title: "Articles on Smashing Magazine — For Web Designers And Developers", url: "https://www.smashingmagazine.com/feed", score: 1.00, category: "ui-ux" },
    { title: "Boxes and Arrows", url: "http://boxesandarrows.com/rss/", score: 0.98, category: "ui-ux" },
    { title: "Designer News Feed", url: "https://www.designernews.co/?format=rss", score: 0.96, category: "ui-ux" },
    { title: "Inside Design", url: "https://www.invisionapp.com/inside-design/feed", score: 0.94, category: "ui-ux" },
    { title: "JUST™ Creative", url: "https://feeds.feedburner.com/JustCreativeDesignBlog", score: 0.92, category: "ui-ux" },
    { title: "NN/g latest articles and announcements", url: "https://www.nngroup.com/feed/rss/", score: 0.90, category: "ui-ux" },
    { title: "UX Blog – UX Studio", url: "https://uxstudioteam.com/ux-blog/feed/", score: 0.88, category: "ui-ux" },
    { title: "UX Collective - Medium", url: "https://uxdesign.cc/feed", score: 0.86, category: "ui-ux" },
    { title: "UX Movement", url: "https://uxmovement.com/feed/", score: 0.84, category: "ui-ux" },
    { title: "Usability Geek", url: "https://usabilitygeek.com/feed/", score: 0.82, category: "ui-ux" },
    { title: "User Experience", url: "https://www.reddit.com/r/userexperience/.rss", score: 0.80, category: "ui-ux" },
  ],
  "web-development": [
    { title: "A List Apart: The Full Feed", url: "https://alistapart.com/main/feed/", score: 1.00, category: "web-development" },
    { title: "CSS-Tricks", url: "https://css-tricks.com/feed/", score: 0.98, category: "web-development" },
    { title: "Code Wall", url: "https://www.codewall.co.uk/feed/", score: 0.96, category: "web-development" },
    { title: "David Walsh Blog", url: "https://davidwalsh.name/feed", score: 0.94, category: "web-development" },
    { title: "Mozilla Hacks – the Web developer blog", url: "https://hacks.mozilla.org/feed/", score: 0.92, category: "web-development" },
    { title: "Sink In - Tech and Travel", url: "https://gosink.in/rss/", score: 0.90, category: "web-development" },
    { title: "Updates", url: "https://developers.google.com/web/updates/rss.xml", score: 0.88, category: "web-development" },
  ],
};

// Country-based news feeds
export const COUNTRY_BASED_FEEDS: Record<string, Feed[]> = {
  "australia": [
    { title: "Latest News and News Headlines | Daily Telegraph", url: "https://www.dailytelegraph.com.au/news/breaking-news/rss", score: 1.00, country: "australia" },
    { title: "Sydney Morning Herald - Latest News", url: "https://www.smh.com.au/rss/feed.xml", score: 0.98, country: "australia" },
    { title: "Latest News and News Headlines | Herald Sun", url: "https://www.heraldsun.com.au/news/breaking-news/rss", score: 0.96, country: "australia" },
    { title: "ABC News", url: "https://www.abc.net.au/news/feed/1948/rss.xml", score: 0.94, country: "australia" },
    { title: "The Age - Latest News", url: "https://www.theage.com.au/rss/feed.xml", score: 0.92, country: "australia" },
    { title: "The Courier Mail", url: "https://www.couriermail.com.au/rss", score: 0.90, country: "australia" },
    { title: "PerthNow", url: "https://www.perthnow.com.au/news/feed", score: 0.88, country: "australia" },
    { title: "The Canberra Times - Local News", url: "https://www.canberratimes.com.au/rss.xml", score: 0.86, country: "australia" },
    { title: "Brisbane Times - Latest News", url: "https://www.brisbanetimes.com.au/rss/feed.xml", score: 0.84, country: "australia" },
    { title: "Independent Australia", url: "http://feeds.feedburner.com/IndependentAustralia", score: 0.82, country: "australia" },
    { title: "Business News - Latest Headlines", url: "https://www.businessnews.com.au/rssfeed/latest.rss", score: 0.80, country: "australia" },
    { title: "InDaily", url: "https://indaily.com.au/feed/", score: 0.78, country: "australia" },
    { title: "The Mercury", url: "https://www.themercury.com.au/rss", score: 0.76, country: "australia" },
    { title: "Crikey", url: "https://feeds.feedburner.com/com/rCTl", score: 0.74, country: "australia" },
    { title: "KUSA - News", url: "http://rssfeeds.9news.com/kusa/home&x=1", score: 0.72, country: "australia" },
    { title: "Michael West", url: "https://www.michaelwest.com.au/feed/", score: 0.70, country: "australia" },
  ],
  "bangladesh": [
    { title: "The Daily Star", url: "https://www.thedailystar.net/frontpage/rss.xml", score: 1.00, country: "bangladesh" },
    { title: "BD24Live.com", url: "https://www.bd24live.com/feed", score: 0.98, country: "bangladesh" },
    { title: "bdnews24.com - Home", url: "https://bdnews24.com/?widgetName=rssfeed&widgetId=1150&getXmlFeed=true", score: 0.96, country: "bangladesh" },
    { title: "Bangla News", url: "https://www.banglanews24.com/rss/rss.xml", score: 0.94, country: "bangladesh" },
    { title: "JUGANTOR", url: "https://www.jugantor.com/feed/rss.xml", score: 0.92, country: "bangladesh" },
    { title: "jagonews24.com | rss Feed", url: "https://www.jagonews24.com/rss/rss.xml", score: 0.90, country: "bangladesh" },
    { title: "kalerkantho Kantho", url: "https://www.kalerkantho.com/rss.xml", score: 0.88, country: "bangladesh" },
    { title: "প্রথম আলো", url: "https://www.prothomalo.com/feed/", score: 0.86, country: "bangladesh" },
  ],
  "brazil": [
    { title: "Folha de S.Paulo - Em cima da hora - Principal", url: "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml", score: 1.00, country: "brazil" },
    { title: "Portal EBC - RSS", url: "http://www.ebc.com.br/rss/feed.xml", score: 0.98, country: "brazil" },
    { title: "R7 - Notícias", url: "https://noticias.r7.com/feed.xml", score: 0.96, country: "brazil" },
    { title: "UOL", url: "http://rss.home.uol.com.br/index.xml", score: 0.94, country: "brazil" },
    { title: "The Rio Times", url: "https://riotimesonline.com/feed/", score: 0.92, country: "brazil" },
    { title: "Brasil Wire", url: "http://www.brasilwire.com/feed/", score: 0.90, country: "brazil" },
    { title: "Jornal de Brasília", url: "https://jornaldebrasilia.com.br/feed/", score: 0.88, country: "brazil" },
  ],
  "canada": [
    { title: "CBC | Top Stories News", url: "https://www.cbc.ca/cmlink/rss-topstories", score: 1.00, country: "canada" },
    { title: "CTVNews.ca - Top Stories - Public RSS", url: "https://www.ctvnews.ca/rss/ctvnews-ca-top-stories-public-rss-1.822009", score: 0.98, country: "canada" },
    { title: "", url: "https://globalnews.ca/feed/", score: 0.96, country: "canada" },
    { title: "Financial Post", url: "https://business.financialpost.com/feed/", score: 0.94, country: "canada" },
    { title: "National Post", url: "https://nationalpost.com/feed/", score: 0.92, country: "canada" },
    { title: "Ottawa Citizen", url: "https://ottawacitizen.com/feed/", score: 0.90, country: "canada" },
    { title: "The Province", url: "https://theprovince.com/feed/", score: 0.88, country: "canada" },
    { title: "LaPresse.ca - Actualités", url: "https://www.lapresse.ca/actualites/rss", score: 0.86, country: "canada" },
    { title: "Toronto Star", url: "https://www.thestar.com/content/thestar/feed.RSSManagerServlet.articles.topstories.rss", score: 0.84, country: "canada" },
    { title: "Toronto Sun - RSS Feed", url: "https://torontosun.com/category/news/feed", score: 0.82, country: "canada" },
  ],
  "germany": [
    { title: "ZEIT ONLINE | Nachrichten, Hintergründe und Debatten", url: "http://newsfeed.zeit.de/index", score: 1.00, country: "germany" },
    { title: "FOCUS Online", url: "https://rss.focus.de/fol/XML/rss_folnews.xml", score: 0.98, country: "germany" },
    { title: "Aktuell - FAZ.NET", url: "https://www.faz.net/rss/aktuell/", score: 0.96, country: "germany" },
    { title: "tagesschau.de - Die Nachrichten der ARD", url: "http://www.tagesschau.de/xml/rss2", score: 0.94, country: "germany" },
    { title: "Deutsche Welle", url: "https://rss.dw.com/rdf/rss-en-all", score: 0.92, country: "germany" },
  ],
  "spain": [
    { title: "The Local", url: "https://feeds.thelocal.com/rss/es", score: 1.00, country: "spain" },
    { title: "EL PAÍS: el periódico global", url: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada", score: 0.98, country: "spain" },
    { title: "España", url: "https://rss.elconfidencial.com/espana/", score: 0.96, country: "spain" },
    { title: "ElDiario.es - ElDiario.es", url: "https://www.eldiario.es/rss/", score: 0.94, country: "spain" },
    { title: "Portada // expansion", url: "https://e00-expansion.uecdn.es/rss/portada.xml", score: 0.92, country: "spain" },
    { title: "El Periódico - portada", url: "https://www.elperiodico.com/es/rss/rss_portada.xml", score: 0.90, country: "spain" },
    { title: "huffingtonpost.es", url: "https://www.huffingtonpost.es/feeds/index.xml", score: 0.88, country: "spain" },
    { title: "Euro Weekly News Spain", url: "https://www.euroweeklynews.com/feed/", score: 0.86, country: "spain" },
    { title: "Agencia EFE | www.efe.com | English edition", url: "https://www.efe.com/efe/english/4/rss", score: 0.84, country: "spain" },
  ],
  "france": [
    { title: "france24.com", url: "https://www.france24.com/en/rss", score: 1.00, country: "france" },
    { title: "Mediapart", url: "https://www.mediapart.fr/articles/feed", score: 0.98, country: "france" },
    { title: "Paris Star", url: "https://www.parisstaronline.com/feed", score: 0.96, country: "france" },
    { title: "Le Monde.fr - Actualités et Infos en France et dans le monde", url: "https://www.lemonde.fr/rss/une.xml", score: 0.94, country: "france" },
    { title: "L'Obs - A la une", url: "https://www.nouvelobs.com/a-la-une/rss.xml", score: 0.92, country: "france" },
    { title: "Franceinfo - Les Titres", url: "https://www.francetvinfo.fr/titres.rss", score: 0.90, country: "france" },
    { title: "Le Huffington Post", url: "https://www.huffingtonpost.fr/feeds/index.xml", score: 0.88, country: "france" },
    { title: "La Dépêche du Midi : actualités et info en direct de la région Occitanie et des environs - ladepeche.fr", url: "https://www.ladepeche.fr/rss.xml", score: 0.86, country: "france" },
    { title: "Ministry for Europe and Foreign Affairs - Actualités", url: "https://www.diplomatie.gouv.fr/spip.php?page=backend-fd&lang=en", score: 0.84, country: "france" },
    { title: "L'essentiel", url: "https://www.sudouest.fr/essentiel/rss.xml", score: 0.82, country: "france" },
    { title: "Ouest-France - Actualité", url: "https://www.ouest-france.fr/rss-en-continu.xml", score: 0.80, country: "france" },
  ],
  "united-kingdom": [
    { title: "BBC News - Home", url: "http://feeds.bbci.co.uk/news/rss.xml", score: 1.00, country: "united-kingdom" },
    { title: "World news | The Guardian", url: "https://www.theguardian.com/world/rss", score: 0.98, country: "united-kingdom" },
    { title: "Home | Mail Online", url: "https://www.dailymail.co.uk/home/index.rss", score: 0.96, country: "united-kingdom" },
    { title: "The Independent", url: "http://www.independent.co.uk/news/uk/rss", score: 0.94, country: "united-kingdom" },
    { title: "Daily Express :: News Feed", url: "http://feeds.feedburner.com/daily-express-news-showbiz", score: 0.92, country: "united-kingdom" },
  ],
  "hong-kong": [
    { title: "Hong Kong Free Press HKFP", url: "https://www.hongkongfp.com/feed/", score: 1.00, country: "hong-kong" },
    { title: "The Standard - Latest News", url: "https://www.thestandard.com.hk/newsfeed/latest/news.xml", score: 0.98, country: "hong-kong" },
    { title: "頭條日報 Headline Daily - 頭條網", url: "https://hd.stheadline.com/rss/news/daily/", score: 0.96, country: "hong-kong" },
    { title: "香港新聞RSS - 香港經濟日報 hket.com", url: "https://www.hket.com/rss/hongkong", score: 0.94, country: "hong-kong" },
    { title: "hongkongnews.net latest rss headlines", url: "http://feeds.hongkongnews.net/rss/b82693edf38ebff8", score: 0.92, country: "hong-kong" },
  ],
  "indonesia": [
    { title: "Republika Online RSS Feed", url: "https://www.republika.co.id/rss/", score: 1.00, country: "indonesia" },
    { title: "Tribunnews.com", url: "https://www.tribunnews.com/rss", score: 0.98, country: "indonesia" },
    { title: "Merdeka.com", url: "https://www.merdeka.com/feed/", score: 0.96, country: "indonesia" },
    { title: "Suara.com", url: "https://www.suara.com/rss", score: 0.94, country: "indonesia" },
  ],
  "ireland": [
    { title: "TheJournal.ie", url: "https://www.thejournal.ie/feed/", score: 1.00, country: "ireland" },
    { title: "All: BreakingNews.ie", url: "https://feeds.breakingnews.ie/bntopstories", score: 0.98, country: "ireland" },
    { title: "The42", url: "https://www.the42.ie/feed/", score: 0.96, country: "ireland" },
    { title: "IrishExaminer.com", url: "https://feeds.feedburner.com/ietopstories", score: 0.94, country: "ireland" },
    { title: "IrishCentral.com - Top Stories", url: "https://feeds.feedburner.com/IrishCentral", score: 0.92, country: "ireland" },
    { title: "Irish Mirror - Home", url: "https://www.irishmirror.ie/?service=rss", score: 0.90, country: "ireland" },
  ],
  "india": [
    { title: "BBC News - India", url: "http://feeds.bbci.co.uk/news/world/asia/india/rss.xml", score: 1.00, country: "india" },
    { title: "India | The Guardian", url: "https://www.theguardian.com/world/india/rss", score: 0.98, country: "india" },
    { title: "SEBI RSS Feed", url: "https://www.sebi.gov.in/sebirss.xml", score: 0.96, country: "india" },
    { title: "Times of India", url: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", score: 0.94, country: "india" },
    { title: "The Hindu - Home", url: "https://www.thehindu.com/feeder/default.rss", score: 0.92, country: "india" },
    { title: "NDTV News -   Topstories", url: "https://feeds.feedburner.com/ndtvnews-top-stories", score: 0.90, country: "india" },
    { title: "India Today | Latest Stories", url: "https://www.indiatoday.in/rss/home", score: 0.88, country: "india" },
    { title: "Front Page | The Indian Express", url: "http://indianexpress.com/print/front-page/feed/", score: 0.86, country: "india" },
    { title: "Top World News- News18.com", url: "https://www.news18.com/rss/world.xml", score: 0.84, country: "india" },
    { title: "India News", url: "https://www.dnaindia.com/feeds/india.xml", score: 0.82, country: "india" },
    { title: "Firstpost India Latest News", url: "https://www.firstpost.com/rss/india.xml", score: 0.80, country: "india" },
    { title: "Home Page", url: "https://www.business-standard.com/rss/home_page_top_stories.rss", score: 0.78, country: "india" },
    { title: "Outlook India", url: "https://www.outlookindia.com/rss/main/magazine", score: 0.76, country: "india" },
    { title: "Free Press Journal", url: "https://www.freepressjournal.in/stories.rss", score: 0.74, country: "india" },
    { title: "Deccan Chronicle - Latest India news | Breaking news | Hyderabad News | World news | Business news | Politics | Technology news", url: "https://www.deccanchronicle.com/rss_feed/", score: 0.72, country: "india" },
    { title: "Moneycontrol Latest News", url: "http://www.moneycontrol.com/rss/latestnews.xml", score: 0.70, country: "india" },
    { title: "Economic Times", url: "https://economictimes.indiatimes.com/rssfeedsdefault.cms", score: 0.68, country: "india" },
    { title: "News, Latest News, Today's News Headlines, Breaking News, LIVE News - Oneindia", url: "https://www.oneindia.com/rss/news-fb.xml", score: 0.66, country: "india" },
    { title: "Scroll.in", url: "http://feeds.feedburner.com/ScrollinArticles.rss", score: 0.64, country: "india" },
    { title: "The Financial Express", url: "https://www.financialexpress.com/feed/", score: 0.62, country: "india" },
    { title: "Business Line - Home", url: "https://www.thehindubusinessline.com/feeder/default.rss", score: 0.60, country: "india" },
    { title: "TechGenyz", url: "http://feeds.feedburner.com/techgenyz", score: 0.58, country: "india" },
    { title: "Top Stories News - Gujarat Samachar : World's Leading Gujarati Newspaper", url: "https://www.gujaratsamachar.com/rss/top-stories", score: 0.56, country: "india" },
    { title: "Marathi News: मराठी बातम्या,  Latest News in Marathi, Breaking Marathi News, Marathi News Paper | Maharashtra Times", url: "https://maharashtratimes.com/rssfeedsdefault.cms", score: 0.54, country: "india" },
    { title: "Loksattaदेश-विदेश &#8211; Loksatta", url: "https://www.loksatta.com/desh-videsh/feed/", score: 0.52, country: "india" },
    { title: "Latest News program News18 Lokmat", url: "https://lokmat.news18.com/rss/program.xml", score: 0.50, country: "india" },
    { title: "OpIndia", url: "https://feeds.feedburner.com/opindia", score: 0.50, country: "india" },
    { title: "ThePrint", url: "https://theprint.in/feed/", score: 0.50, country: "india" },
    { title: "Swarajya", url: "https://prod-qt-images.s3.amazonaws.com/production/swarajya/feed.xml", score: 0.50, country: "india" },
    { title: "Latest And Breaking Hindi News Headlines, News In Hindi | अमर उजाला हिंदी न्यूज़ | - Amar Ujala", url: "https://www.amarujala.com/rss/breaking-news.xml", score: 0.50, country: "india" },
    { title: "Navbharat Times", url: "https://navbharattimes.indiatimes.com/rssfeedsdefault.cms", score: 0.50, country: "india" },
    { title: "Patrika : India's Leading Hindi News Portal", url: "http://api.patrika.com/rss/india-news", score: 0.50, country: "india" },
    { title: "JansattaJansatta", url: "https://www.jansatta.com/feed/", score: 0.50, country: "india" },
    { title: "Live Hindustan Rss feed", url: "https://feed.livehindustan.com/rss/3127", score: 0.50, country: "india" },
    { title: "देश | दैनिक भास्कर", url: "https://www.bhaskar.com/rss-feed/1061/", score: 0.50, country: "india" },
    { title: "ઈન્ડિયા | દિવ્ય ભાસ્કર", url: "https://www.divyabhaskar.co.in/rss-feed/1037/", score: 0.50, country: "india" },
  ],
  "iran": [
    { title: "خبرگزاری باشگاه خبرنگاران | آخرین اخبار ایران و جهان | YJC", url: "https://www.yjc.ir/fa/rss/allnews", score: 1.00, country: "iran" },
    { title: "تابناک | TABNAK", url: "https://www.tabnak.ir/fa/rss/allnews", score: 0.98, country: "iran" },
    { title: "خبرگزاری ایسنا | صفحه اصلی |  ISNA News Agency", url: "https://www.isna.ir/rss", score: 0.96, country: "iran" },
    { title: "خبرگزاری مهر | اخبار ایران و جهان | Mehr News Agency", url: "https://www.mehrnews.com/rss", score: 0.94, country: "iran" },
    { title: "خبرگزاری خبرآنلاین - آخرین اخبار ایران و جهان | Khabaronline", url: "https://www.khabaronline.ir/rss", score: 0.92, country: "iran" },
    { title: "اخبار ایران و جهان", url: "https://www.tasnimnews.com/fa/rss/feed/0/8/0/%D9%85%D9%87%D9%85%D8%AA%D8%B1%DB%8C%D9%86-%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1-%D8%AA%D8%B3%D9%86%DB%8C%D9%85", score: 0.90, country: "iran" },
    { title: "عصر ايران", url: "https://www.asriran.com/fa/rss/allnews", score: 0.88, country: "iran" },
  ],
  "italy": [
    { title: "RSS di   - ANSA.it", url: "https://www.ansa.it/sito/ansait_rss.xml", score: 1.00, country: "italy" },
    { title: "The Local", url: "https://feeds.thelocal.com/rss/it", score: 0.98, country: "italy" },
    { title: "RSS DiariodelWeb.it", url: "https://www.diariodelweb.it/rss/home/", score: 0.96, country: "italy" },
    { title: "Fanpage", url: "https://www.fanpage.it/feed/", score: 0.94, country: "italy" },
    { title: "Libero Quotidiano", url: "https://www.liberoquotidiano.it/rss.xml", score: 0.92, country: "italy" },
    { title: "Il Mattino Web", url: "https://www.ilmattino.it/?sez=XML&args&p=search&args[box]=Home&limit=20&layout=rss", score: 0.90, country: "italy" },
    { title: "Adnkronos - ultimoratop", url: "http://rss.adnkronos.com/RSS_PrimaPagina.xml", score: 0.88, country: "italy" },
    { title: "Milan News", url: "https://www.milannews.it/rss/", score: 0.86, country: "italy" },
    { title: "Internazionale", url: "https://www.internazionale.it/sitemaps/rss.xml", score: 0.84, country: "italy" },
    { title: "Panorama", url: "https://www.panorama.it/feeds/feed.rss", score: 0.82, country: "italy" },
    { title: "Italy | The Guardian", url: "https://www.theguardian.com/world/italy/rss", score: 0.80, country: "italy" },
    { title: "Il Post", url: "https://www.ilpost.it/feed/", score: 0.78, country: "italy" },
  ],
  "japan": [
    { title: "Japan Times latest articles", url: "https://www.japantimes.co.jp/feed/topstories/", score: 1.00, country: "japan" },
    { title: "Japan Today", url: "https://japantoday.com/feed", score: 0.98, country: "japan" },
    { title: "News On Japan", url: "http://www.newsonjapan.com/rss/top.xml", score: 0.96, country: "japan" },
    { title: "All - Kyodo News+", url: "https://english.kyodonews.net/rss/all.xml", score: 0.94, country: "japan" },
    { title: "BRIDGE（ブリッジ）テクノロジー＆スタートアップ情報", url: "http://feeds.feedburner.com/SdJapan", score: 0.92, country: "japan" },
    { title: "ライブドアニュース - 主要トピックス", url: "https://news.livedoor.com/topics/rss/top.xml", score: 0.90, country: "japan" },
    { title: "朝日新聞デジタル", url: "http://rss.asahi.com/rss/asahi/newsheadlines.rdf", score: 0.88, country: "japan" },
  ],
  "myanmar": [
    { title: "Myanmar Gazette News Media Forum Network", url: "http://myanmargazette.net/feed", score: 1.00, country: "myanmar" },
    { title: "DVB Multimedia Group", url: "http://www.dvb.no/feed", score: 0.98, country: "myanmar" },
    { title: "THIT HTOO LWIN (Daily News)", url: "http://www.thithtoolwin.com/feeds/posts/default", score: 0.96, country: "myanmar" },
  ],
  "mexico": [
    { title: "Mexico | The Guardian", url: "https://www.theguardian.com/world/mexico/rss", score: 1.00, country: "mexico" },
    { title: "Excélsior - RSS", url: "https://www.excelsior.com.mx/rss.xml", score: 0.98, country: "mexico" },
    { title: "Reforma", url: "https://www.reforma.com/rss/portada.xml", score: 0.96, country: "mexico" },
    { title: "Lo último en Vanguardia MX", url: "https://vanguardia.com.mx/rss.xml", score: 0.94, country: "mexico" },
    { title: "Portada, El Siglo de Torreón", url: "https://www.elsiglodetorreon.com.mx/index.xml", score: 0.92, country: "mexico" },
    { title: "El Financiero", url: "https://www.elfinanciero.com.mx/arc/outboundfeeds/rss/?outputType=xml", score: 0.90, country: "mexico" },
    { title: "ElNorte", url: "https://www.elnorte.com/rss/portada.xml", score: 0.88, country: "mexico" },
    { title: "El Informador :: Noticias de Jalisco, México, Deportes & Entretenimiento", url: "https://www.informador.mx/rss/ultimas-noticias.xml", score: 0.86, country: "mexico" },
    { title: "24 Horas", url: "https://www.24-horas.mx/feed/", score: 0.84, country: "mexico" },
    { title: "Tu Periódico Quequi", url: "https://quequi.com.mx/feed/", score: 0.82, country: "mexico" },
    { title: "DEBATE", url: "https://www.debate.com.mx/rss/feed.xml", score: 0.80, country: "mexico" },
    { title: "Mexico News Daily", url: "https://mexiconewsdaily.com/feed/", score: 0.78, country: "mexico" },
    { title: "El Diario", url: "https://diario.mx/jrz/media/sitemaps/rss.xml", score: 0.76, country: "mexico" },
    { title: "8 Columnas", url: "https://8columnas.com.mx/feed/", score: 0.74, country: "mexico" },
    { title: "", url: "https://www.eluniversal.com.mx/seccion/1671/rss.xml", score: 0.72, country: "mexico" },
  ],
  "nigeria": [
    { title: "All Content", url: "http://saharareporters.com/feeds/latest/feed", score: 1.00, country: "nigeria" },
    { title: "Nigeria News Links | Today's Updates - Nigerian Bulletin", url: "https://www.nigerianbulletin.com/forums/-/index.rss", score: 0.98, country: "nigeria" },
    { title: "Nigerian News. Latest Nigeria News. Your online Nigerian Newspaper.", url: "http://feeds.feedburner.com/Nigerianeye", score: 0.96, country: "nigeria" },
    { title: "Legit.ng", url: "https://www.legit.ng/rss/all.rss", score: 0.94, country: "nigeria" },
    { title: "Latest Nigeria News, Nigerian Newspapers, Politics", url: "https://thenationonlineng.net/feed/", score: 0.92, country: "nigeria" },
    { title: "Daily Post Nigeria", url: "https://dailypost.ng/feed", score: 0.90, country: "nigeria" },
    { title: "Premium Times Nigeria", url: "https://www.premiumtimesng.com/feed", score: 0.88, country: "nigeria" },
    { title: "Information Nigeria", url: "https://www.informationng.com/feed", score: 0.86, country: "nigeria" },
    { title: "The Guardian Nigeria News – Nigeria and World News", url: "https://guardian.ng/feed/", score: 0.84, country: "nigeria" },
    { title: "Tribune Online", url: "http://tribuneonlineng.com/feed/", score: 0.82, country: "nigeria" },
  ],
  "philippines": [
    { title: "INQUIRER.net", url: "https://www.inquirer.net/fullfeed", score: 1.00, country: "philippines" },
    { title: "Latest News | Philippine Information Agency", url: "https://pia.gov.ph/news/feed.rss", score: 0.98, country: "philippines" },
    { title: "Interaksyon", url: "https://www.interaksyon.com/feed/", score: 0.96, country: "philippines" },
    { title: "- The Manila Times", url: "https://www.manilatimes.net/rssfeed/", score: 0.94, country: "philippines" },
    { title: "philstar.com - RSS Headlines", url: "https://www.philstar.com/rss/headlines", score: 0.92, country: "philippines" },
    { title: "BusinessWorld", url: "https://www.bworldonline.com/feed/", score: 0.90, country: "philippines" },
    { title: "https://www.sunstar.com.ph/", url: "https://www.sunstar.com.ph/rssFeed/selected", score: 0.88, country: "philippines" },
    { title: "PhilNews.XYZ", url: "https://www.philnews.xyz/feeds/posts/default?alt=rss", score: 0.86, country: "philippines" },
    { title: "Manila Standard", url: "https://manilastandard.net/feed/all", score: 0.84, country: "philippines" },
    { title: "GMA News Online / News", url: "https://data.gmanews.tv/gno/rss/news/feed.xml", score: 0.82, country: "philippines" },
    { title: "Current PH", url: "https://currentph.com/feed/", score: 0.80, country: "philippines" },
    { title: "Top Gear: The Philippine authority on cars and the automotive industry", url: "https://www.topgear.com.ph/feed/rss1", score: 0.78, country: "philippines" },
    { title: "Eagle News", url: "https://www.eaglenews.ph/feed/", score: 0.76, country: "philippines" },
    { title: "UNBOX PH", url: "https://www.unbox.ph/feed/", score: 0.74, country: "philippines" },
    { title: "Tempo – The Nation's Fastest Growing Newspaper", url: "http://tempo.com.ph/feed/", score: 0.72, country: "philippines" },
    { title: "Abante Tonite", url: "https://tonite.abante.com.ph/feed/", score: 0.70, country: "philippines" },
    { title: "BusinessMirror", url: "https://businessmirror.com.ph/feed/", score: 0.68, country: "philippines" },
    { title: "Latest News | Philippine News Agency", url: "https://www.pna.gov.ph/latest.rss", score: 0.66, country: "philippines" },
    { title: "TechPinas : Philippines' Technology News, Tips and Reviews Blog", url: "http://feeds.feedburner.com/Techpinas", score: 0.64, country: "philippines" },
    { title: "BICOL STANDARD | Bicol News | Bicol Newspaper", url: "http://www.bicolstandard.com/feeds/posts/default?alt=rss", score: 0.62, country: "philippines" },
  ],
  "pakistan": [
    { title: "The Express Tribune", url: "https://tribune.com.pk/feed/home", score: 1.00, country: "pakistan" },
    { title: "The Nation - Top Stories", url: "https://nation.com.pk/rss/top-stories", score: 0.98, country: "pakistan" },
    { title: "قومی خبریں", url: "https://jang.com.pk/rss/1/1", score: 0.96, country: "pakistan" },
    { title: "The News International - Pakistan", url: "https://www.thenews.com.pk/rss/1/1", score: 0.94, country: "pakistan" },
    { title: "News Blog", url: "https://newsnblogs.com/feed/", score: 0.92, country: "pakistan" },
    { title: "UrduPoint.com All Urdu News", url: "https://www.urdupoint.com/rss/urdupoint.rss", score: 0.90, country: "pakistan" },
    { title: "ایکسپریس اردو", url: "https://www.express.pk/feed/", score: 0.88, country: "pakistan" },
  ],
  "poland": [
    { title: "Najnowsze", url: "http://feeds.feedburner.com/wPolitycepl", score: 1.00, country: "poland" },
    { title: "Newsweek Polska", url: "https://www.newsweek.pl/rss.xml", score: 0.98, country: "poland" },
    { title: "Dziennik.pl Dziennik - dziennik.pl", url: "http://rss.dziennik.pl/Dziennik-PL/", score: 0.96, country: "poland" },
    { title: "www.wirtualnemedia.pl", url: "https://www.wirtualnemedia.pl/rss/wirtualnemedia_rss.xml", score: 0.94, country: "poland" },
    { title: "GazetaPrawna.pl - biznes, podatki, prawo, finanse, wiadomości, praca", url: "http://rss.gazetaprawna.pl/GazetaPrawna", score: 0.92, country: "poland" },
    { title: "https://www.rp.pl", url: "https://www.rp.pl/rss/1019", score: 0.90, country: "poland" },
    { title: "Polska Agencja Prasowa SA", url: "https://www.pap.pl/rss.xml", score: 0.88, country: "poland" },
    { title: "RMF24.pl", url: "https://www.rmf24.pl/feed", score: 0.86, country: "poland" },
  ],
  "russia": [
    { title: "Lenta.ru : Новости", url: "https://lenta.ru/rss", score: 1.00, country: "russia" },
    { title: "Вести.Ru", url: "https://www.vesti.ru/vesti.rss", score: 0.98, country: "russia" },
    { title: "Газета.Ru - Первая полоса", url: "https://www.gazeta.ru/export/rss/first.xml", score: 0.96, country: "russia" },
    { title: "Все материалы - Московский Комсомолец", url: "https://www.mk.ru/rss/index.xml", score: 0.94, country: "russia" },
    { title: "Российская Газета", url: "https://rg.ru/xml/index.xml", score: 0.92, country: "russia" },
    { title: "NEWSru.com :: Главные новости", url: "https://rss.newsru.com/top/big/", score: 0.90, country: "russia" },
    { title: "RT - Daily news", url: "https://www.rt.com/rss/", score: 0.88, country: "russia" },
    { title: "Meduza.io", url: "https://meduza.io/rss/all", score: 0.86, country: "russia" },
    { title: "Russia Insider Daily Headlines", url: "https://russia-insider.com/en/all-content/rss", score: 0.84, country: "russia" },
    { title: "TASS", url: "http://tass.com/rss/v2.xml", score: 0.82, country: "russia" },
    { title: "The Moscow Times - Independent News From Russia", url: "https://www.themoscowtimes.com/rss/news", score: 0.80, country: "russia" },
    { title: "Газета ", url: "https://www.kommersant.ru/RSS/main.xml", score: 0.78, country: "russia" },
    { title: "PravdaReport", url: "https://www.pravdareport.com/export.xml", score: 0.76, country: "russia" },
  ],
  "ukraine": [
    { title: "News Agency UNIAN", url: "https://rss.unian.net/site/news_eng.rss", score: 1.00, country: "ukraine" },
    { title: "ТЕЛЕГРАФ - последние новости Украины и мира", url: "https://telegraf.com.ua/yandex-feed/", score: 0.98, country: "ukraine" },
    { title: "Последние новости на сайте korrespondent.net", url: "http://k.img.com.ua/rss/ru/all_news2.0.xml", score: 0.96, country: "ukraine" },
    { title: "Цензор.НЕТ - Новости", url: "https://censor.net.ua/includes/news_ru.xml", score: 0.94, country: "ukraine" },
    { title: "Новини на tsn.ua", url: "https://tsn.ua/rss/full.rss", score: 0.92, country: "ukraine" },
    { title: "Українська правда", url: "https://www.pravda.com.ua/rss/", score: 0.90, country: "ukraine" },
    { title: "Гордон - Самые популярные материалы", url: "https://gordonua.com/xml/rss_category/top.html", score: 0.88, country: "ukraine" },
    { title: "НВ", url: "https://nv.ua/rss/all.xml", score: 0.86, country: "ukraine" },
    { title: "Информационное агентство УНИАН", url: "https://rss.unian.net/site/news_rus.rss", score: 0.84, country: "ukraine" },
    { title: "Еспресо - український погляд на світ!", url: "https://espreso.tv/rss", score: 0.82, country: "ukraine" },
    { title: "Gazeta.ua", url: "https://gazeta.ua/rss", score: 0.80, country: "ukraine" },
    { title: "Вести.ua", url: "https://vesti.ua/feeds/partners", score: 0.78, country: "ukraine" },
  ],
  "united-states": [
    { title: "World News - Breaking News, Top Stories", url: "https://www.huffpost.com/section/world-news/feed", score: 1.00, country: "united-states" },
    { title: "FOX News", url: "http://feeds.foxnews.com/foxnews/latest", score: 0.98, country: "united-states" },
    { title: "World", url: "http://feeds.washingtonpost.com/rss/world", score: 0.96, country: "united-states" },
    { title: "WSJ.com: World News", url: "https://feeds.a.dj.com/rss/RSSWorldNews.xml", score: 0.94, country: "united-states" },
    { title: "World & Nation", url: "https://www.latimes.com/world-nation/rss2.0.xml", score: 0.92, country: "united-states" },
    { title: "CNN.com - RSS Channel - App International Edition", url: "http://rss.cnn.com/rss/edition.rss", score: 0.90, country: "united-states" },
    { title: "Yahoo News - Latest News & Headlines", url: "https://news.yahoo.com/rss/mostviewed", score: 0.88, country: "united-states" },
    { title: "US Top News and Analysis", url: "https://www.cnbc.com/id/100003114/device/rss/rss.html", score: 0.86, country: "united-states" },
    { title: "Playbook", url: "https://rss.politico.com/playbook.xml", score: 0.84, country: "united-states" },
  ],
  "south-africa": [
    { title: "SowetanLIVE", url: "https://www.sowetanlive.co.za/rss/?publication=sowetan-live", score: 1.00, country: "south-africa" },
    { title: "TechCentral", url: "https://techcentral.co.za/feed", score: 0.98, country: "south-africa" },
    { title: "News24 Top Stories", url: "http://feeds.news24.com/articles/news24/TopStories/rss", score: 0.96, country: "south-africa" },
    { title: "Eyewitness News | Latest News", url: "https://ewn.co.za/RSS%20Feeds/Latest%20News", score: 0.94, country: "south-africa" },
    { title: "The Citizen", url: "https://citizen.co.za/feed/", score: 0.92, country: "south-africa" },
    { title: "Daily Maverick", url: "https://www.dailymaverick.co.za/dmrss/", score: 0.90, country: "south-africa" },
    { title: "Moneyweb", url: "https://www.moneyweb.co.za/feed/", score: 0.88, country: "south-africa" },
    { title: "IOL section feed for News", url: "http://rss.iol.io/iol/news", score: 0.86, country: "south-africa" },
    { title: "TimesLIVE", url: "https://www.timeslive.co.za/rss/", score: 0.84, country: "south-africa" },
    { title: "The South African", url: "https://www.thesouthafrican.com/feed/", score: 0.82, country: "south-africa" },
    { title: "Axios", url: "https://api.axios.com/feed/", score: 0.80, country: "south-africa" },
  ],
};

// Fallback feeds when no specific match is found
export const FALLBACK_FEEDS: Feed[] = [
  { title: "Accidental Tech Podcast", url: "https://atp.fm/rss", score: 0.95 },
  { title: "Analog(ue)", url: "https://www.relay.fm/analogue/feed", score: 0.90 },
  { title: "BBC News - World", url: "http://feeds.bbci.co.uk/news/world/rss.xml", score: 0.95 },
  { title: "CNN.com - RSS Channel - World", url: "http://rss.cnn.com/rss/edition_world.rss", score: 0.90 },
  { title: "Better Programming - Medium", url: "https://medium.com/feed/better-programming", score: 0.95 },
  { title: "Code as Craft", url: "https://codeascraft.com/feed/atom/", score: 0.90 },
  { title: "60-Second Science", url: "http://rss.sciam.com/sciam/60secsciencepodcast", score: 0.95 },
  { title: "BBC News - Science & Environment", url: "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml", score: 0.90 },
  { title: "All News", url: "https://www.investing.com/rss/news.rss", score: 0.95 },
  { title: "Bloomberg Quicktake", url: "https://www.youtube.com/feeds/videos.xml?user=Bloomberg", score: 0.90 },
];
